// 由 `mise run bindings` 產生，不要手改。

// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	openProject: (path: string) => typedError<Snapshot_Serialize, Failure>(__TAURI_INVOKE("open_project", { path })),
	/**
	 *  重新檢查目前開著的專案。
	 * 
	 *  前端會在使用者改動後去抖動地呼叫這個——實測數百條連線是毫秒級，
	 *  所以不需要進度回報。見 `docs/scale-limits.md`。
	 */
	recheck: () => typedError<Snapshot_Serialize, Failure>(__TAURI_INVOKE("recheck")),
	saveProject: () => typedError<Snapshot_Serialize, Failure>(__TAURI_INVOKE("save_project")),
	/**  讀一張表，算出「如果匯進去會發生什麼」。**不改動任何東西。** */
	previewImport: (path: string) => typedError<Plan, Failure>(__TAURI_INVOKE("preview_import", { path })),
	/**
	 *  套用剛剛預覽過的那一份。
	 * 
	 *  走 `History::replace` 而不是直接換掉專案——匯入會動到成百上千個地方，
	 *  是最需要「按錯了能退回去」的操作。
	 */
	applyImport: () => typedError<Snapshot_Serialize, Failure>(__TAURI_INVOKE("apply_import")),
	cancelImport: () => typedError<null, Failure>(__TAURI_INVOKE("cancel_import")),
	/**
	 *  「如果做這次修改，lint 會多出什麼、少掉什麼」。**不改動任何東西。**
	 * 
	 *  刪除之前一定要先問這個。判斷不在這裡——這一層只是轉接。
	 */
	previewEdit: (edit: Edit) => typedError<Impact_Serialize, Failure>(__TAURI_INVOKE("preview_edit", { edit })),
	applyEdit: (edit: Edit) => typedError<Snapshot_Serialize, Failure>(__TAURI_INVOKE("apply_edit", { edit })),
	/**
	 *  把 lint 面板上「照著修法填的那一格」變成一次修改。
	 * 
	 *  前端送回來的是**發現本身 + 使用者填了什麼**，不是 [`Edit`]——
	 *  「L006 的答案要寫進哪個欄位」由 `loom_core::edit::edit_for` 決定。
	 *  前端因此完全不需要知道 [`Edit`] 有哪些變體。
	 */
	applyFix: (finding: Finding_Deserialize, value: FixValue) => typedError<Snapshot_Serialize, Failure>(__TAURI_INVOKE("apply_fix", { finding, value })),
	/**
	 *  退回上一步。已經到底了就原樣回傳——這不是錯誤，
	 *  使用者多按一次 Cmd+Z 不該看到紅字。
	 */
	undo: () => typedError<Snapshot_Serialize, Failure>(__TAURI_INVOKE("undo")),
	redo: () => typedError<Snapshot_Serialize, Failure>(__TAURI_INVOKE("redo")),
};

/* Types */
/**  矩陣裡的一格。 */
export type Cell = {
	relationship: Id,
	environment: Id,
	status: Status,
	/**
	 *  這條契約在這個環境被拆成幾段實際連線。
	 *  dev 直連是 1，prod 走 F5 是 2。
	 */
	segments: number,
	/**  目標端展開成幾個 Instance。萬用字元會展開成一整群。 */
	targets: number,
	/**  目標端註明的期望數量。`None` 代表沒用萬用字元，或用了卻沒註明。 */
	expect: number | null,
	/**  這格對應到哪些 lint 規則。畫面上點下去就能跳到 lint 面板。 */
	rules: Rule[],
};

export type Change = {
	kind: ChangeKind,
	element: Element,
	/**  人看得懂的位置，例如 `prod / redis-01`。 */
	label: string,
	/**  更新前的值。新增時是 `None`。 */
	before: string | null,
	after: string,
};

export type ChangeKind = "added" | "updated";

/**
 *  環境層的一條實際連線。
 * 
 *  `serves` 指向它所服務的邏輯 [`Relationship`](crate::logical::Relationship)。
 *  Lint 把貼同一個 `serves` 的連線攤開成一張圖，檢查從來源走不走得到目標。
 */
export type Connection = Connection_Serialize | Connection_Deserialize;

/**
 *  連線一端指向的 Instance：可以是一個，也可以是一整群。
 *  連線的哪一端。
 * 
 *  # 為什麼需要指名
 * 
 *  一條連線的兩端**都可能是萬用字元**（`apigw-* → common-*`），
 *  所以「這條連線的期望數量不對」是個不完整的說法——它沒說是哪一端。
 *  Lint 的發現、以及照著發現去修的那次編輯，都必須指名，
 *  否則就得用猜的，而猜錯會安靜地改到另一端。
 * 
 *  名字不叫 `Side`，是為了不跟 [`crate::table::Side`]（表格上一端的完整樣貌）
 *  撞名——型別匯出到 TypeScript 之後是同一個命名空間，撞了就產不出來。
 */
export type ConnectionEnd = "from" | "to";

/**  連線是正常路徑還是備援路徑。 */
export type ConnectionKind = 
/**  平常就在走的路。預設。 */
"primary" | 
/**
 *  只在故障時才走。**它一樣要被建立、防火牆一樣要開**——
 *  所以 lint 對它的要求跟正常路徑完全相同，差別只在畫面上的呈現。
 */
"fallback";

/**
 *  環境層的一條實際連線。
 * 
 *  `serves` 指向它所服務的邏輯 [`Relationship`](crate::logical::Relationship)。
 *  Lint 把貼同一個 `serves` 的連線攤開成一張圖，檢查從來源走不走得到目標。
 */
export type Connection_Deserialize = {
	id: Id,
	serves: Id,
	/**  用途說明。空白會觸發 L007。 */
	purpose: string,
	/**
	 *  這是平常走的路，還是只在故障時走的。
	 * 
	 *  「同中心優先、某中心出問題才交叉」這種安排會讓一條契約長出四條連線，
	 *  其中兩條是備援。沒有這個欄位的話四條看起來一樣重，圖上會很吵，
	 *  讀的人也分不出平常的資料流是哪幾條。
	 */
	kind?: ConnectionKind,
	from: Endpointing_Deserialize,
	to: Endpointing_Deserialize,
};

/**
 *  環境層的一條實際連線。
 * 
 *  `serves` 指向它所服務的邏輯 [`Relationship`](crate::logical::Relationship)。
 *  Lint 把貼同一個 `serves` 的連線攤開成一張圖，檢查從來源走不走得到目標。
 */
export type Connection_Serialize = {
	id: Id,
	serves: Id,
	/**  用途說明。空白會觸發 L007。 */
	purpose: string,
	/**
	 *  這是平常走的路，還是只在故障時走的。
	 * 
	 *  「同中心優先、某中心出問題才交叉」這種安排會讓一條契約長出四條連線，
	 *  其中兩條是備援。沒有這個欄位的話四條看起來一樣重，圖上會很吵，
	 *  讀的人也分不出平常的資料流是哪幾條。
	 */
	kind?: ConnectionKind,
	from: Endpointing_Serialize,
	to: Endpointing_Serialize,
};

/**  一個會跑的服務：Redis、Consul、訂單 API。C4 的 `Container`。 */
export type Container = Container_Serialize | Container_Deserialize;

/**
 *  邏輯 Container 在此環境的一份落地。C4 的 `Container Instance`。
 * 
 *  叢集就是多個 Instance：12 台 VM 各跑一個 Redis process
 *  就是 12 個 `ContainerInstance`。節點數不另外存數字，避免兩份資料不一致。
 */
export type ContainerInstance = ContainerInstance_Serialize | ContainerInstance_Deserialize;

/**
 *  邏輯 Container 在此環境的一份落地。C4 的 `Container Instance`。
 * 
 *  叢集就是多個 Instance：12 台 VM 各跑一個 Redis process
 *  就是 12 個 `ContainerInstance`。節點數不另外存數字，避免兩份資料不一致。
 */
export type ContainerInstance_Deserialize = {
	id: Id,
	slug: string,
	container: Id,
	endpoints?: Endpoint_Deserialize[],
	/**
	 *  標記「刻意獨立」，關閉 L008（沒被任何連線碰到）的警告。
	 *  冷備機是合法情境，但預設應該要叫。
	 */
	standalone?: boolean,
};

/**
 *  邏輯 Container 在此環境的一份落地。C4 的 `Container Instance`。
 * 
 *  叢集就是多個 Instance：12 台 VM 各跑一個 Redis process
 *  就是 12 個 `ContainerInstance`。節點數不另外存數字，避免兩份資料不一致。
 */
export type ContainerInstance_Serialize = {
	id: Id,
	slug: string,
	container: Id,
	endpoints?: Endpoint_Serialize[],
	/**
	 *  標記「刻意獨立」，關閉 L008（沒被任何連線碰到）的警告。
	 *  冷備機是合法情境，但預設應該要叫。
	 */
	standalone?: boolean,
};

/**  一個會跑的服務：Redis、Consul、訂單 API。C4 的 `Container`。 */
export type Container_Deserialize = {
	id: Id,
	slug: string,
	name: string,
	system: Id,
	endpoints?: EndpointDef[],
};

/**  一個會跑的服務：Redis、Consul、訂單 API。C4 的 `Container`。 */
export type Container_Serialize = {
	id: Id,
	slug: string,
	name: string,
	system: Id,
	endpoints?: EndpointDef[],
};

/**  機器：實體機、VM、Linux container。C4 的 `Deployment Node`，可巢狀。 */
export type DeploymentNode = DeploymentNode_Serialize | DeploymentNode_Deserialize;

/**  機器：實體機、VM、Linux container。C4 的 `Deployment Node`，可巢狀。 */
export type DeploymentNode_Deserialize = {
	id: Id,
	slug: string,
	kind: NodeKind,
	/**  巢狀：機房 → 機器 → 容器。 */
	children?: DeploymentNode_Deserialize[],
	instances?: ContainerInstance_Deserialize[],
};

/**  機器：實體機、VM、Linux container。C4 的 `Deployment Node`，可巢狀。 */
export type DeploymentNode_Serialize = {
	id: Id,
	slug: string,
	kind: NodeKind,
	/**  巢狀：機房 → 機器 → 容器。 */
	children?: DeploymentNode_Serialize[],
	instances?: ContainerInstance_Serialize[],
};

/**  對專案的一次修改。 */
export type Edit = 
/**
 *  L006 的修法：補上某個 Endpoint 的實際位址。
 * 
 *  Endpoint 可能掛在 Instance、設備或外部系統落地上，所以只給 id，
 *  由 [`apply`] 自己找。前端不需要知道它住在哪一層。
 */
({ setAddress: {
	environment: Id,
	endpoint: Id,
	/**
	 *  `None` 表示清空。清空是合法操作——它會讓 L006 重新叫，
	 *  那正是「我還不知道位址」該有的狀態。
	 */
	address: string | null,
} }) & { deleteConnection?: never; setConnectionKind?: never; setExpect?: never; setPurpose?: never; setStandalone?: never } | 
/**
 *  L007 的修法：填上用途。
 * 
 *  `environment` 為 `None` 時指的是邏輯層的 Relationship。
 */
({ setPurpose: {
	environment: Id | null,
	subject: Id,
	purpose: string,
} }) & { deleteConnection?: never; setAddress?: never; setConnectionKind?: never; setExpect?: never; setStandalone?: never } | 
/**  L004 / L005 的修法：萬用字元的期望數量。 */
({ setExpect: {
	environment: Id,
	connection: Id,
	side: ConnectionEnd,
	expect: number | null,
} }) & { deleteConnection?: never; setAddress?: never; setConnectionKind?: never; setPurpose?: never; setStandalone?: never } | 
/**  L008 的修法：標記「刻意獨立」，例如冷備機。 */
({ setStandalone: {
	environment: Id,
	/**  Instance 或外部系統落地的 id。 */
	subject: Id,
	standalone: boolean,
} }) & { deleteConnection?: never; setAddress?: never; setConnectionKind?: never; setExpect?: never; setPurpose?: never } | 
/**  改成正常路徑或備援路徑。 */
({ setConnectionKind: {
	environment: Id,
	connection: Id,
	kind: ConnectionKind,
} }) & { deleteConnection?: never; setAddress?: never; setExpect?: never; setPurpose?: never; setStandalone?: never } | 
/**
 *  刪掉一條環境層連線。
 * 
 *  這是目前唯一的刪除操作，而且刪除一定要先看 [`preview`]——
 *  少一條連線正是本工具存在要抓的東西。
 */
({ deleteConnection: {
	environment: Id,
	connection: Id,
} }) & { setAddress?: never; setConnectionKind?: never; setExpect?: never; setPurpose?: never; setStandalone?: never };

/**  動到的是什麼東西。畫面上用來分組。 */
export type Element = "environment" | 
/**  邏輯層的服務。 */
"container" | 
/**  邏輯層的接點定義。 */
"endpointDef" | 
/**  邏輯層的連線契約。 */
"relationship" | "deploymentNode" | "containerInstance" | 
/**  某個 Endpoint 的實際位址。 */
"address" | "infrastructureNode" | "softwareSystemInstance" | "connection";

/**  Endpoint 在某環境的實際樣貌：定義加上位址。 */
export type Endpoint = Endpoint_Serialize | Endpoint_Deserialize;

/**
 *  Endpoint 的定義：只有名字與協定，沒有位址。
 * 
 *  位址屬於環境層的 [`Endpoint`](crate::environment::Endpoint)。
 */
export type EndpointDef = {
	id: Id,
	slug: string,
	protocol: Protocol,
};

/**  Endpoint 在某環境的實際樣貌：定義加上位址。 */
export type Endpoint_Deserialize = {
	id: Id,
	slug: string,
	/**
	 *  對應邏輯層的 `EndpointDef`。
	 *  [`InfrastructureNode`] 的 endpoint 沒有邏輯層對應，此處為 `None`。
	 */
	def?: Id | null,
	protocol: Protocol,
	/**
	 *  `10.0.1.11:6379` / JDBC URL / socket 路徑 / 檔案路徑。
	 *  缺少會觸發 L006，所以必須允許 `None`。
	 */
	address: string | null,
};

/**  Endpoint 在某環境的實際樣貌：定義加上位址。 */
export type Endpoint_Serialize = {
	id: Id,
	slug: string,
	/**
	 *  對應邏輯層的 `EndpointDef`。
	 *  [`InfrastructureNode`] 的 endpoint 沒有邏輯層對應，此處為 `None`。
	 */
	def?: Id | null,
	protocol: Protocol,
	/**
	 *  `10.0.1.11:6379` / JDBC URL / socket 路徑 / 檔案路徑。
	 *  缺少會觸發 L006，所以必須允許 `None`。
	 */
	address: string | null,
};

/**
 *  連線的一端。
 * 
 *  YAML 上長這樣（`serves` 相同的連線串起來就是一條路徑）：
 * 
 *  ```yaml
 *  from:
 *    instance:
 *      target: { one: i-prod-api-01 }   # 來源不填 endpoint = OS 分配
 *  to:
 *    infra:
 *      node: f5-prod
 *      endpoint: ep-f5-redis
 *  ```
 */
export type Endpointing = Endpointing_Serialize | Endpointing_Deserialize;

/**
 *  連線的一端。
 * 
 *  YAML 上長這樣（`serves` 相同的連線串起來就是一條路徑）：
 * 
 *  ```yaml
 *  from:
 *    instance:
 *      target: { one: i-prod-api-01 }   # 來源不填 endpoint = OS 分配
 *  to:
 *    infra:
 *      node: f5-prod
 *      endpoint: ep-f5-redis
 *  ```
 */
export type Endpointing_Deserialize = ({ instance: {
	/**
	 *  欄位叫 `target` 而不是 `instance`，否則 YAML 會出現
	 *  `instance: { instance: ... }` 這種讀不下去的巢狀。
	 */
	target: InstanceRef_Deserialize,
	/**
	 *  指向**邏輯層的 [`EndpointDef`](crate::logical::EndpointDef)**，
	 *  不是某一台的具體 [`Endpoint`]。
	 * 
	 *  因為萬用字元會展開成多台 Instance，各有各的具體 endpoint；
	 *  只有邏輯層的定義才是它們共通的東西。實際位址由各 Instance
	 *  上 `def` 對應的那個 endpoint 提供。
	 * 
	 *  來源端可為 `None`，表示由作業系統分配（ephemeral port）。
	 */
	endpoint?: Id | null,
} }) & { infra?: never; person?: never; system?: never } | ({ infra: {
	node: Id,
	/**
	 *  指向該設備上的具體 [`Endpoint`] id。
	 * 
	 *  與 Instance 端不對稱是刻意的：設備不對應任何邏輯層元素，
	 *  它的 endpoint（VIP 位址）沒有 `EndpointDef` 可以指。
	 */
	endpoint?: Id | null,
} }) & { instance?: never; person?: never; system?: never } | 
/**  外部系統。不支援萬用字元——一個外部系統在一個環境就是一個落地。 */
({ system: {
	instance: Id,
	/**
	 *  同 Instance 端，指向邏輯層的 `EndpointDef`（掛在
	 *  [`SoftwareSystem`](crate::logical::SoftwareSystem) 上）。
	 */
	endpoint?: Id | null,
} }) & { infra?: never; instance?: never; person?: never } | 
/**
 *  真人。只會出現在**來源端**——使用者是流量的起點。
 * 
 *  人沒有落地也沒有位址，所以這一端只指向邏輯層的
 *  [`Person`](crate::logical::Person)，沒有 endpoint。
 *  「使用者從哪裡連過來」不是我們配置得到的東西。
 */
({ person: {
	person: Id,
} }) & { infra?: never; instance?: never; system?: never };

/**
 *  連線的一端。
 * 
 *  YAML 上長這樣（`serves` 相同的連線串起來就是一條路徑）：
 * 
 *  ```yaml
 *  from:
 *    instance:
 *      target: { one: i-prod-api-01 }   # 來源不填 endpoint = OS 分配
 *  to:
 *    infra:
 *      node: f5-prod
 *      endpoint: ep-f5-redis
 *  ```
 */
export type Endpointing_Serialize = ({ instance: {
	/**
	 *  欄位叫 `target` 而不是 `instance`，否則 YAML 會出現
	 *  `instance: { instance: ... }` 這種讀不下去的巢狀。
	 */
	target: InstanceRef_Serialize,
	/**
	 *  指向**邏輯層的 [`EndpointDef`](crate::logical::EndpointDef)**，
	 *  不是某一台的具體 [`Endpoint`]。
	 * 
	 *  因為萬用字元會展開成多台 Instance，各有各的具體 endpoint；
	 *  只有邏輯層的定義才是它們共通的東西。實際位址由各 Instance
	 *  上 `def` 對應的那個 endpoint 提供。
	 * 
	 *  來源端可為 `None`，表示由作業系統分配（ephemeral port）。
	 */
	endpoint?: Id | null,
} }) & { infra?: never; person?: never; system?: never } | ({ infra: {
	node: Id,
	/**
	 *  指向該設備上的具體 [`Endpoint`] id。
	 * 
	 *  與 Instance 端不對稱是刻意的：設備不對應任何邏輯層元素，
	 *  它的 endpoint（VIP 位址）沒有 `EndpointDef` 可以指。
	 */
	endpoint?: Id | null,
} }) & { instance?: never; person?: never; system?: never } | 
/**  外部系統。不支援萬用字元——一個外部系統在一個環境就是一個落地。 */
({ system: {
	instance: Id,
	/**
	 *  同 Instance 端，指向邏輯層的 `EndpointDef`（掛在
	 *  [`SoftwareSystem`](crate::logical::SoftwareSystem) 上）。
	 */
	endpoint?: Id | null,
} }) & { infra?: never; instance?: never; person?: never } | 
/**
 *  真人。只會出現在**來源端**——使用者是流量的起點。
 * 
 *  人沒有落地也沒有位址，所以這一端只指向邏輯層的
 *  [`Person`](crate::logical::Person)，沒有 endpoint。
 *  「使用者從哪裡連過來」不是我們配置得到的東西。
 */
({ person: {
	person: Id,
} }) & { infra?: never; instance?: never; system?: never };

/**  一個部署環境。 */
export type Environment = Environment_Serialize | Environment_Deserialize;

/**  一個部署環境。 */
export type Environment_Deserialize = {
	id: Id,
	slug: string,
	name: string,
	nodes?: DeploymentNode_Deserialize[],
	infra?: InfrastructureNode_Deserialize[],
	/**  外部系統在此環境的落地。不在 `nodes` 底下，因為那些機器不是我們的。 */
	systems?: SoftwareSystemInstance_Deserialize[],
	connections?: Connection_Deserialize[],
};

/**  一個部署環境。 */
export type Environment_Serialize = {
	id: Id,
	slug: string,
	name: string,
	nodes?: DeploymentNode_Serialize[],
	infra?: InfrastructureNode_Serialize[],
	/**  外部系統在此環境的落地。不在 `nodes` 底下，因為那些機器不是我們的。 */
	systems?: SoftwareSystemInstance_Serialize[],
	connections?: Connection_Serialize[],
};

/**
 *  前端拿到的錯誤。
 * 
 *  只是字串——使用者需要的是「哪裡出錯、怎麼修」，不是錯誤型別的階層。
 */
export type Failure = {
	message: string,
};

/**
 *  一項發現。
 * 
 *  欄位順序即排序順序，讓 lint 的輸出穩定可比對。
 */
export type Finding = Finding_Serialize | Finding_Deserialize;

/**
 *  一項發現，外加它的嚴重度與修法。
 * 
 *  `Rule::severity()` 在 Rust 是一個方法，序列化不會帶過去。若讓前端自己
 *  抄一份「哪些規則算錯誤」的對照表，新增規則時那份一定會忘記更新，
 *  而且是**靜靜地**算錯數字。所以在這裡攤平成欄位。
 * 
 *  `fix` 同理：「L006 要填的是位址、L004 要填的是數字」是規則不是畫面，
 *  由 `loom_core::edit::fix_for` 決定，前端只負責照著長出控制項。
 */
export type FindingView = {
	rule: Rule,
	severity: Severity,
	environment: Id | null,
	subject: Id,
	/**
	 *  問題出在連線的哪一端。前端不需要看懂它，但**必須原樣送回來**——
	 *  兩端都是萬用字元時，少了它就分不出這一項在講哪一端。
	 */
	end: ConnectionEnd | null,
	detail: string,
	/**
	 *  這一項能不能用單一欄位修好，以及該長成什麼樣的輸入。
	 *  `None` 表示要新增／改接連線，不是填一格能解決的。
	 */
	fix: Fix | null,
};

/**
 *  一項發現。
 * 
 *  欄位順序即排序順序，讓 lint 的輸出穩定可比對。
 */
export type Finding_Deserialize = {
	rule: Rule,
	/**  發生在哪個環境；邏輯層本身的問題為 `None`。 */
	environment: Id | null,
	/**  出問題的元素。 */
	subject: Id,
	/**
	 *  問題出在連線的哪一端。
	 * 
	 *  # 為什麼不能省
	 * 
	 *  一條連線的兩端都可能是萬用字元（`apigw-* → common-*`），
	 *  於是同一條連線會產生**兩項 rule 與 subject 都相同的 L004**。
	 *  少了這個欄位，「照著發現去修」就只能猜是哪一端——
	 *  而猜錯會安靜地改到另一端，使用者按了套用卻什麼都沒發生。
	 * 
	 *  跟連線的端點無關的規則（L001／L006／L007／L008）是 `None`。
	 */
	end?: ConnectionEnd | null,
	detail: string,
};

/**
 *  一項發現。
 * 
 *  欄位順序即排序順序，讓 lint 的輸出穩定可比對。
 */
export type Finding_Serialize = {
	rule: Rule,
	/**  發生在哪個環境；邏輯層本身的問題為 `None`。 */
	environment: Id | null,
	/**  出問題的元素。 */
	subject: Id,
	/**
	 *  問題出在連線的哪一端。
	 * 
	 *  # 為什麼不能省
	 * 
	 *  一條連線的兩端都可能是萬用字元（`apigw-* → common-*`），
	 *  於是同一條連線會產生**兩項 rule 與 subject 都相同的 L004**。
	 *  少了這個欄位，「照著發現去修」就只能猜是哪一端——
	 *  而猜錯會安靜地改到另一端，使用者按了套用卻什麼都沒發生。
	 * 
	 *  跟連線的端點無關的規則（L001／L006／L007／L008）是 `None`。
	 */
	end?: ConnectionEnd | null,
	detail: string,
};

/**
 *  這項發現該用哪種控制項來修。
 * 
 *  只描述「長什麼樣的輸入」，不描述畫面細節——畫面是前端的事，
 *  但「L006 要填的是位址不是數字」是規則，屬於這裡。
 */
export type Fix = 
/**  填一段文字（位址、用途）。 */
({ text: {
	/**  欄位提示，例如「10.0.1.11:6379」。 */
	hint: string,
	current: string | null,
} }) & { count?: never; toggle?: never } | 
/**  填一個數字（expect）。附上實際符合的數量當預設值。 */
({ count: {
	suggestion: number | null,
} }) & { text?: never; toggle?: never } | 
/**  一個開關（standalone）。 */
({ toggle: {
	label: string,
} }) & { count?: never; text?: never };

/**  使用者在 [`Fix`] 的控制項裡填的東西。 */
export type FixValue = ({ text: string }) & { count?: never; toggle?: never } | ({ count: number | null }) & { text?: never; toggle?: never } | ({ toggle: boolean }) & { count?: never; text?: never };

/**  元素的永久識別碼。建立後永不改變。 */
export type Id = string;

/**  [`preview`] 的結果：這次修改會弄壞什麼、會修好什麼。 */
export type Impact = Impact_Serialize | Impact_Deserialize;

/**  [`preview`] 的結果：這次修改會弄壞什麼、會修好什麼。 */
export type Impact_Deserialize = {
	/**  套用後**新冒出來**的發現。刪除確認框要顯眼地列出這些。 */
	introduced: Finding_Deserialize[],
	/**  套用後**消失**的發現。 */
	resolved: Finding_Deserialize[],
};

/**  [`preview`] 的結果：這次修改會弄壞什麼、會修好什麼。 */
export type Impact_Serialize = {
	/**  套用後**新冒出來**的發現。刪除確認框要顯眼地列出這些。 */
	introduced: Finding_Serialize[],
	/**  套用後**消失**的發現。 */
	resolved: Finding_Serialize[],
};

/**
 *  F5 等 VIP 設備。C4 的 `Infrastructure Node`。
 * 
 *  它**不含 Container**，但有自己的 endpoint（VIP 位址），
 *  因此連線可以「經過」它——這也是為什麼經過 F5 的流量會拆成兩段。
 */
export type InfrastructureNode = InfrastructureNode_Serialize | InfrastructureNode_Deserialize;

/**
 *  F5 等 VIP 設備。C4 的 `Infrastructure Node`。
 * 
 *  它**不含 Container**，但有自己的 endpoint（VIP 位址），
 *  因此連線可以「經過」它——這也是為什麼經過 F5 的流量會拆成兩段。
 */
export type InfrastructureNode_Deserialize = {
	id: Id,
	slug: string,
	endpoints?: Endpoint_Deserialize[],
};

/**
 *  F5 等 VIP 設備。C4 的 `Infrastructure Node`。
 * 
 *  它**不含 Container**，但有自己的 endpoint（VIP 位址），
 *  因此連線可以「經過」它——這也是為什麼經過 F5 的流量會拆成兩段。
 */
export type InfrastructureNode_Serialize = {
	id: Id,
	slug: string,
	endpoints?: Endpoint_Serialize[],
};

export type InstanceRef = InstanceRef_Serialize | InstanceRef_Deserialize;

export type InstanceRef_Deserialize = 
/**  指名一個 Instance。 */
({ one: Id }) & { pattern?: never } | 
/**
 *  萬用字元，例如 `redis-*`。
 * 
 *  `expect` 是期望數量。**它必須是 `Option`**：萬用字元表示「現在有幾台就
 *  連幾台」，少建一台 VM 會看起來完全正常，正好吃掉本工具的核心價值。
 *  因此沒填 `expect` 要能被 lint 抓出來（L005），型別就不能強制它存在。
 */
({ pattern: {
	slug_pattern: string,
	/**
	 *  只算這個 [`DeploymentNode`] 底下的（含所有子孫）。
	 * 
	 *  # 為什麼需要它
	 * 
	 *  `redis-* expect 6` 只數總量。有人把一台機器從主中心搬到異地，
	 *  總數還是 6，**lint 不會叫**——而那正是這個工具存在的理由。
	 * 
	 *  拆成兩條「主中心 3 台」「異地 3 台」就抓得到。而站點資訊
	 *  **本來就在模型裡**（Instance 住在 VM 裡，VM 住在站點裡），
	 *  所以不需要新的 Cluster 概念，只需要能限定範圍。
	 * 
	 *  順帶好處：站點不必再編進 slug（`redis-main-01`）。
	 *  名字編了資訊就會說謊——機器搬家之後 slug 不會自己改。
	 */
	within?: Id | null,
	/**
	 *  用 `u32` 而不是 `usize`：這是「期望有幾台機器」，不是記憶體索引。
	 *  而且 `usize` 不能匯出成 TypeScript（specta 怕 BigInt 精度問題）。
	 */
	expect?: number | null,
} }) & { one?: never };

export type InstanceRef_Serialize = 
/**  指名一個 Instance。 */
({ one: Id }) & { pattern?: never } | 
/**
 *  萬用字元，例如 `redis-*`。
 * 
 *  `expect` 是期望數量。**它必須是 `Option`**：萬用字元表示「現在有幾台就
 *  連幾台」，少建一台 VM 會看起來完全正常，正好吃掉本工具的核心價值。
 *  因此沒填 `expect` 要能被 lint 抓出來（L005），型別就不能強制它存在。
 */
({ pattern: {
	slug_pattern: string,
	/**
	 *  只算這個 [`DeploymentNode`] 底下的（含所有子孫）。
	 * 
	 *  # 為什麼需要它
	 * 
	 *  `redis-* expect 6` 只數總量。有人把一台機器從主中心搬到異地，
	 *  總數還是 6，**lint 不會叫**——而那正是這個工具存在的理由。
	 * 
	 *  拆成兩條「主中心 3 台」「異地 3 台」就抓得到。而站點資訊
	 *  **本來就在模型裡**（Instance 住在 VM 裡，VM 住在站點裡），
	 *  所以不需要新的 Cluster 概念，只需要能限定範圍。
	 * 
	 *  順帶好處：站點不必再編進 slug（`redis-main-01`）。
	 *  名字編了資訊就會說謊——機器搬家之後 slug 不會自己改。
	 */
	within?: Id | null,
	/**
	 *  用 `u32` 而不是 `usize`：這是「期望有幾台機器」，不是記憶體索引。
	 *  而且 `usize` 不能匯出成 TypeScript（specta 怕 BigInt 精度問題）。
	 */
	expect?: number | null,
} }) & { one?: never };

/**  邏輯層的全部內容。 */
export type Logical = Logical_Serialize | Logical_Deserialize;

/**  邏輯層的全部內容。 */
export type Logical_Deserialize = {
	people: Person[],
	systems: SoftwareSystem_Deserialize[],
	containers: Container_Deserialize[],
	relationships: Relationship[],
};

/**  邏輯層的全部內容。 */
export type Logical_Serialize = {
	people: Person[],
	systems: SoftwareSystem_Serialize[],
	containers: Container_Serialize[],
	relationships: Relationship[],
};

/**  整張矩陣。列是邏輯連線，欄是環境。 */
export type Matrix = {
	/**  列的順序，與 `project.logical.relationships` 相同。 */
	relationships: Id[],
	/**  欄的順序，與 `project.environments` 相同。 */
	environments: Id[],
	/**  每格一項，依 (relationship, environment) 排列，長度為兩者相乘。 */
	cells: Cell[],
};

/**  運算載體的種類。 */
export type NodeKind = 
/**
 *  機房、園區、可用區——**裝別的節點用的**，本身不跑東西。
 * 
 *  C4 的 Deployment Node 本來就可巢狀，站點是它最常見的外層用法。
 *  沒有這個種類的話，「主中心」只能勉強標成實體機，畫出來會變成一台機器。
 */
"site" | "physical" | "virtual-machine" | "linux-container";

/**  真人使用者。C4 的 `Person`，只出現在 Context 圖。 */
export type Person = {
	id: Id,
	slug: string,
	name: string,
};

export type Plan = {
	changes: Change[],
	/**  檔案裡有、但內容完全相同的項目數。重新匯入時這個數字會很大。 */
	unchanged: number,
	/**  importer 自己的計數與警告（例如位址衝突）。 */
	warnings: string[],
	/**  這份檔案會動到哪些環境。 */
	environments: string[],
};

/**
 *  一個專案：一份邏輯層母版，加上多個環境。
 *  一個完整的專案。
 * 
 *  存檔時會被 [`repository`] 拆成多個 YAML 檔，所以磁碟上沒有「一個 Project 檔」。
 *  但它整份會跨過 Tauri 邊界送到前端當唯讀鏡像，因此需要序列化。
 */
export type Project = Project_Serialize | Project_Deserialize;

/**
 *  一個專案：一份邏輯層母版，加上多個環境。
 *  一個完整的專案。
 * 
 *  存檔時會被 [`repository`] 拆成多個 YAML 檔，所以磁碟上沒有「一個 Project 檔」。
 *  但它整份會跨過 Tauri 邊界送到前端當唯讀鏡像，因此需要序列化。
 */
export type Project_Deserialize = {
	id: Id,
	slug: string,
	name: string,
	logical: Logical_Deserialize,
	environments: Environment_Deserialize[],
};

/**
 *  一個專案：一份邏輯層母版，加上多個環境。
 *  一個完整的專案。
 * 
 *  存檔時會被 [`repository`] 拆成多個 YAML 檔，所以磁碟上沒有「一個 Project 檔」。
 *  但它整份會跨過 Tauri 邊界送到前端當唯讀鏡像，因此需要序列化。
 */
export type Project_Serialize = {
	id: Id,
	slug: string,
	name: string,
	logical: Logical_Serialize,
	environments: Environment_Serialize[],
};

/**
 *  Endpoint 的協定種類。
 * 
 *  「Port」這個詞不夠準確——Unix socket、JDBC URL 與檔案都不是 port，
 *  它們的共通點是「服務對外的一個接點」，因此統一叫 Endpoint。
 */
export type Protocol = "tcp" | "udp" | "unix-socket" | "jdbc" | "file";

/**
 *  邏輯層的連線：「A 要連 B 的某個 endpoint」，並說明用途。
 * 
 *  **這就是原本討論中的「連線契約」。** 我們刻意不另設 placeholder 概念——
 *  邏輯層宣告了一條連線，每個環境就必須實現它，沒實現就是 lint 錯誤。
 * 
 *  一條 Relationship 在不同環境會展開成**不同數量**的實際連線：
 *  dev 直連是 1 段，prod 走 F5 是 2 段；Redis 叢集 prod 12 個節點、test 6 個。
 */
export type Relationship = {
	id: Id,
	slug: string,
	/**  用途說明。空白會觸發 L007。 */
	purpose: string,
	from: RelationshipEnd,
	to: RelationshipEnd,
	/**
	 *  連到目標的哪一個 [`EndpointDef`]。
	 *  目標是 Container 就查它的 endpoints，是外部系統就查系統的 endpoints。
	 */
	to_endpoint: Id,
};

/**
 *  邏輯連線的一端：自家的服務、一整個外部系統，或一個真人。
 * 
 *  外部系統不拆成 Container，所以它整個就是一端。
 */
export type RelationshipEnd = ({ container: Id }) & { person?: never; system?: never } | ({ system: Id }) & { container?: never; person?: never } | 
/**
 *  真人。**只該出現在來源端**——「使用者連上系統」是 C4 Context 圖
 *  最常見的關係，沒有它整條進入點的流量就少了最前面那一段。
 * 
 *  人不需要被部署，所以 L001 不會要求它在每個環境都有落地。
 */
({ person: Id }) & { container?: never; system?: never };

/**  表格的一列。 */
export type Row = {
	id: Id,
	environment: Id,
	/**  它服務哪條契約。 */
	serves: Id,
	/**  契約的顯示名。找不到對應契約時是 `None`（那本身就是 L003）。 */
	servesSlug: string | null,
	purpose: string,
	/**
	 *  正常路徑還是備援路徑。畫面上用來區分——備援跟正常長得一樣的話，
	 *  讀的人分不出平常的資料流是哪幾條。
	 */
	kind: ConnectionKind,
	from: Side,
	to: Side,
	/**  這一列自己的嚴重度。沒問題時是 `None`。 */
	severity: Severity | null,
	rules: Rule[],
	/**
	 *  這一列牽涉到的所有模型元素 id：連線自己、它服務的契約、
	 *  兩端解析出來的 Instance／設備／外部系統／人，以及用到的 Endpoint。
	 * 
	 *  # 為什麼需要它
	 * 
	 *  Lint 面板上點一項發現，要能跳到**那一列**。但發現的 `subject`
	 *  不一定是連線 id——L006 指的是 Endpoint、L008 指的是 Instance。
	 *  「這個 id 對應到哪幾列」得走一次萬用字元展開才知道，
	 *  那跟 lint 是同一套邏輯，放前端就是寫第二遍。
	 */
	subjects: Id[],
};

/**  規則代號。序列化後就是 `"L001"` 這種字串，跟文件一致。 */
export type Rule = 
/**  邏輯層元素在某環境沒有任何實現。 */
"L001" | 
/**  某條 Relationship 在某環境走不通（可達性斷裂）。 */
"L002" | 
/**  連線指向不存在的 Instance、設備或 Endpoint。 */
"L003" | 
/**  萬用字元的實際數量與 `expect` 不符。 */
"L004" | 
/**  萬用字元沒有註明 `expect`。 */
"L005" | 
/**  Endpoint 缺少實際位址。 */
"L006" | 
/**  連線沒有填用途。 */
"L007" | 
/**  某 Instance 沒有被任何連線碰到。 */
"L008";

export type Severity = "info" | "warning" | "error";

/**  連線的一端，已經解析成看得懂的東西。 */
export type Side = {
	kind: SideKind,
	/**  顯示名。萬用字元保留原樣（`redis-*`），使用者才看得出這是一群。 */
	label: string,
	/**  接點的顯示名。來源端可以沒有（由 OS 分配 ephemeral port）。 */
	endpoint: string | null,
	/**  實際位址。萬用字元會有多個。 */
	addresses: string[],
	/**  萬用字元展開成幾個。不是萬用字元時是 1。 */
	matched: number,
	/**  註明的期望數量。 */
	expect: number | null,
};

/**  連線的一端指向什麼。畫面上用不同的圖示區分。 */
export type SideKind = 
/**  一台或一群服務落地。 */
"instance" | 
/**  F5 這類設備。 */
"infra" | 
/**  外部系統的落地。 */
"system" | 
/**  真人。只會出現在來源端。 */
"person";

/**
 *  開一個專案之後，前端需要的所有東西一次給齊。
 * 
 *  分成三個 command 來回問會有中間狀態（模型換了但 lint 還是舊的），
 *  畫面就會短暫地自相矛盾。
 */
export type Snapshot = Snapshot_Serialize | Snapshot_Deserialize;

/**
 *  開一個專案之後，前端需要的所有東西一次給齊。
 * 
 *  分成三個 command 來回問會有中間狀態（模型換了但 lint 還是舊的），
 *  畫面就會短暫地自相矛盾。
 */
export type Snapshot_Deserialize = {
	root: string,
	project: Project_Deserialize,
	findings: FindingView[],
	matrix: Matrix,
	/**  連線表用的列。跟矩陣一樣，是同一份資料的另一種排法。 */
	rows: Row[],
	/**  目前內容跟磁碟上不一樣。關視窗前要問的就是這個。 */
	dirty: boolean,
	/**  復原／重做選單要顯示的短標籤。`None` 表示按鈕要停用。 */
	undoLabel: string | null,
	redoLabel: string | null,
};

/**
 *  開一個專案之後，前端需要的所有東西一次給齊。
 * 
 *  分成三個 command 來回問會有中間狀態（模型換了但 lint 還是舊的），
 *  畫面就會短暫地自相矛盾。
 */
export type Snapshot_Serialize = {
	root: string,
	project: Project_Serialize,
	findings: FindingView[],
	matrix: Matrix,
	/**  連線表用的列。跟矩陣一樣，是同一份資料的另一種排法。 */
	rows: Row[],
	/**  目前內容跟磁碟上不一樣。關視窗前要問的就是這個。 */
	dirty: boolean,
	/**  復原／重做選單要顯示的短標籤。`None` 表示按鈕要停用。 */
	undoLabel: string | null,
	redoLabel: string | null,
};

/**  軟體系統。可能是自家系統，也可能是外部系統（金流、簡訊商）。 */
export type SoftwareSystem = SoftwareSystem_Serialize | SoftwareSystem_Deserialize;

/**
 *  外部系統在此環境的落地。C4 的 `Software System Instance`。
 * 
 *  例如金流系統：prod 用正式閘道，test 用 sandbox。
 *  它**不放在 [`DeploymentNode`] 底下**——那些機器不是我們的，我們只知道位址。
 */
export type SoftwareSystemInstance = SoftwareSystemInstance_Serialize | SoftwareSystemInstance_Deserialize;

/**
 *  外部系統在此環境的落地。C4 的 `Software System Instance`。
 * 
 *  例如金流系統：prod 用正式閘道，test 用 sandbox。
 *  它**不放在 [`DeploymentNode`] 底下**——那些機器不是我們的，我們只知道位址。
 */
export type SoftwareSystemInstance_Deserialize = {
	id: Id,
	slug: string,
	system: Id,
	endpoints?: Endpoint_Deserialize[],
	/**  同 [`ContainerInstance::standalone`]，關閉 L008 警告。 */
	standalone?: boolean,
};

/**
 *  外部系統在此環境的落地。C4 的 `Software System Instance`。
 * 
 *  例如金流系統：prod 用正式閘道，test 用 sandbox。
 *  它**不放在 [`DeploymentNode`] 底下**——那些機器不是我們的，我們只知道位址。
 */
export type SoftwareSystemInstance_Serialize = {
	id: Id,
	slug: string,
	system: Id,
	endpoints?: Endpoint_Serialize[],
	/**  同 [`ContainerInstance::standalone`]，關閉 L008 警告。 */
	standalone?: boolean,
};

/**  軟體系統。可能是自家系統，也可能是外部系統（金流、簡訊商）。 */
export type SoftwareSystem_Deserialize = {
	id: Id,
	slug: string,
	name: string,
	/**
	 *  外部系統不由我們部署，但仍需在每個環境指定它的落地位址
	 *  （例如測試環境用金流 sandbox）。
	 */
	external: boolean,
	/**
	 *  外部系統對外的接點定義。
	 * 
	 *  C4 不把外部系統拆成 Container——我們看不到人家內部長怎樣，
	 *  只知道「有一個 API 可以打」。因此接點直接掛在系統上。
	 *  自家系統留空，它的接點由各個 [`Container`] 自己定義。
	 */
	endpoints?: EndpointDef[],
};

/**  軟體系統。可能是自家系統，也可能是外部系統（金流、簡訊商）。 */
export type SoftwareSystem_Serialize = {
	id: Id,
	slug: string,
	name: string,
	/**
	 *  外部系統不由我們部署，但仍需在每個環境指定它的落地位址
	 *  （例如測試環境用金流 sandbox）。
	 */
	external: boolean,
	/**
	 *  外部系統對外的接點定義。
	 * 
	 *  C4 不把外部系統拆成 Container——我們看不到人家內部長怎樣，
	 *  只知道「有一個 API 可以打」。因此接點直接掛在系統上。
	 *  自家系統留空，它的接點由各個 [`Container`] 自己定義。
	 */
	endpoints?: EndpointDef[],
};

/**  一格的狀態。畫面上用顏色區分，順序即嚴重度。 */
export type Status = 
/**  沒有任何問題。 */
"realized" | 
/**  有警告，但路是通的。 */
"warning" | 
/**  有錯誤，但至少畫了連線。例如走不通、數量對不上。 */
"broken" | 
/**  這個環境完全沒有實現這條契約——**這就是使用者最怕的那格**。 */
"missing";

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

