// 由 `mise run bindings` 產生，不要手改。

// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	openProject: (path: string) => typedError<OpenOutcome_Serialize, Failure>(__TAURI_INVOKE("open_project", { path })),
	/**
	 *  重新檢查目前開著的專案。
	 * 
	 *  前端會在使用者改動後去抖動地呼叫這個——實測數百條連線是毫秒級，
	 *  所以不需要進度回報。見 `docs/scale-limits.md`。
	 */
	recheck: () => typedError<Snapshot_Serialize, Failure>(__TAURI_INVOKE("recheck")),
	saveProject: () => typedError<Snapshot_Serialize, Failure>(__TAURI_INVOKE("save_project")),
	/**  讀一張表，算出「如果匯進去會發生什麼」。**不改動任何東西。** */
	previewImport: (path: string) => typedError<Plan, Failure>(__TAURI_INVOKE("preview_import", { path })),
	/**
	 *  套用剛剛預覽過的那一份。
	 * 
	 *  走 `History::replace` 而不是直接換掉專案——匯入會動到成百上千個地方，
	 *  是最需要「按錯了能退回去」的操作。
	 */
	applyImport: () => typedError<Snapshot_Serialize, Failure>(__TAURI_INVOKE("apply_import")),
	cancelImport: () => typedError<null, Failure>(__TAURI_INVOKE("cancel_import")),
	/**
	 *  「如果做這次修改，lint 會多出什麼、少掉什麼」。**不改動任何東西。**
	 * 
	 *  刪除之前一定要先問這個。判斷不在這裡——這一層只是轉接。
	 */
	previewEdit: (edit: Edit_Deserialize) => typedError<Impact_Serialize, Failure>(__TAURI_INVOKE("preview_edit", { edit })),
	applyEdit: (edit: Edit_Deserialize) => typedError<Snapshot_Serialize, Failure>(__TAURI_INVOKE("apply_edit", { edit })),
	/**
	 *  照契約擬一條「這個環境應該要有」的連線。**不改動任何東西。**
	 * 
	 *  L001／L002 的修法。判斷全在 `loom_core::connect`——
	 *  哪幾台機器算數、多台要不要收成萬用字元，都是模型知識。
	 */
	proposeConnection: (environment: Id, relationship: Id) => typedError<Proposal_Serialize, Failure>(__TAURI_INVOKE("propose_connection", { environment, relationship })),
	/**  這個環境裡，某一端接得上的所有地方。 */
	connectionChoices: (environment: Id, end: ConnectionEnd) => typedError<Choice_Serialize[], Failure>(__TAURI_INVOKE("connection_choices", { environment, end })),
	/**
	 *  算出「這批會建出什麼」，並且擋掉會撞名的。**不改動任何東西。**
	 * 
	 *  L001 報在**服務**上時的修法（那個服務在這個環境一台都還沒建）。
	 */
	previewBatch: (environment: Id, spec: BatchSpec) => typedError<BatchPlan_Serialize, Failure>(__TAURI_INVOKE("preview_batch", { environment, spec })),
	/**
	 *  資源清單：每種資源一張表。
	 * 
	 *  欄位與格子都是 Rust 算好的——「這個服務在各環境幾台」要走一次實體比對，
	 *  那是模型知識，放前端就是把 `coverage` 再寫一遍。
	 */
	resourceTables: (environment: string | null) => typedError<Table_Serialize[], Failure>(__TAURI_INVOKE("resource_tables", { environment })),
	/**
	 *  一個環境裡的連線展開成圖上要畫的線。
	 * 
	 *  # 為什麼是獨立的 command，不塞進 [`Snapshot`]
	 * 
	 *  萬用字元是 N×M——12 台連 12 台就是 144 條。整份專案的展開結果
	 *  可能比模型本身還大，而它只有「圖」這個檢視在看。塞進 snapshot 的話
	 *  每一次編輯都要付這個代價。
	 */
	diagramLinks: (environment: Id) => typedError<Link[], Failure>(__TAURI_INVOKE("diagram_links", { environment })),
	/**
	 *  篩選面板要列的契約，以及照目前的勾選「誰該亮」。
	 * 
	 *  兩件事一次給：分開問的話，畫面會有一瞬間拿舊的清單配新的亮法。
	 */
	diagramFocus: (environment: Id, focus: Focus) => typedError<FocusView, Failure>(__TAURI_INVOKE("diagram_focus", { environment, focus })),
	/**
	 *  圖上還沒指定的形狀可以指給哪個模型元素。
	 * 
	 *  # 為什麼要把圖上的東西送過來
	 * 
	 *  「哪些元素還沒被用掉」需要同時知道模型與**這張圖**，而圖只有前端手上有
	 *  （它住在編輯器裡，不是磁碟上）。所以 JS 說「圖上有這些形狀、這些已經綁著
	 *  了」，這裡回答「這代表什麼」——跟對帳同一條分界線。
	 */
	diagramTargets: (environment: Id, bound: Id[], shapes: UnboundShape[]) => typedError<Annotation, Failure>(__TAURI_INVOKE("diagram_targets", { environment, bound, shapes })),
	diagramCatalog: (environment: Id) => typedError<DiagramsView, Failure>(__TAURI_INVOKE("diagram_catalog", { environment })),
	/**  讀一張存過的圖，連同它是照哪一版模型畫的。 */
	diagramRead: (environment: Id, name: string) => typedError<Loaded, Failure>(__TAURI_INVOKE("diagram_read", { environment, name })),
	/**  使用者自己建一張新圖。名字不可以是 App 保留的那個。 */
	diagramCreate: (environment: Id, name: string, xml: string) => typedError<DiagramInfo, Failure>(__TAURI_INVOKE("diagram_create", { environment, name, xml })),
	/**  存檔。**模型變了就不存**，判斷在 `diagrams::save`。 */
	diagramSave: (environment: Id, name: string, xml: string, drawnFrom: string) => typedError<string, Failure>(__TAURI_INVOKE("diagram_save", { environment, name, xml, drawnFrom })),
	/**
	 *  一個空白的新資源，給表單當起點。
	 * 
	 *  id 在這裡就發好，所以 `apply` 是決定性的——復原之後重做會得到
	 *  同一個元素，而不是一個新 UUID。
	 */
	blankResource: (kind: Kind, environment: string | null, owner: string | null) => typedError<Resource_Serialize, Failure>(__TAURI_INVOKE("blank_resource", { kind, environment, owner })),
	/**
	 *  在一個空資料夾裡開一個新專案。
	 * 
	 *  # 為什麼要求資料夾是空的
	 * 
	 *  這個操作會在裡面寫 `project.yaml` 與 `logical/`。選到一個已經有東西的
	 *  資料夾（例如使用者的家目錄）就會蓋掉別人的檔案，而那沒辦法復原。
	 */
	createProject: (path: string, name: string) => typedError<Snapshot_Serialize, Failure>(__TAURI_INVOKE("create_project", { path, name })),
	/**
	 *  再開一扇空視窗。
	 * 
	 *  # 為什麼由 Rust 開，不是前端自己開
	 * 
	 *  前端呼叫 `WebviewWindow.create()` 需要 `core:webview:allow-create-webview-window`
	 *  這個權限，而 `capabilities/default.json` 是安全邊界不是設定樣板——
	 *  從 Rust 開就完全不需要它。
	 * 
	 *  label 用遞增的數字。它只是視窗的名字，**不是專案的身分**——
	 *  專案的身分是資料夾路徑，兩者由登記簿配起來。
	 */
	newWindow: () => typedError<null, Failure>(__TAURI_INVOKE("new_window")),
	/**
	 *  打開給 AI Agent 用的本機端點。
	 * 
	 *  判斷與工具都在 `loom-mcp`，這裡只負責開關與把狀態交給畫面。
	 * 
	 *  **開了就記住。** 開關本身就是「我要不要這個端點」這個偏好，
	 *  不需要旁邊再放一個「而且下次也要」——理由見 `mcp::remember`。
	 */
	startMcp: () => typedError<McpStatus, Failure>(__TAURI_INVOKE("start_mcp")),
	stopMcp: () => typedError<McpStatus, Failure>(__TAURI_INVOKE("stop_mcp")),
	mcpStatus: () => typedError<McpStatus, Failure>(__TAURI_INVOKE("mcp_status")),
	/**
	 *  給使用者複製到 Agent 設定檔裡的那一段 JSON。**含 token。**
	 * 
	 *  token 只從這裡出去，狀態查詢不會帶——狀態會被畫面到處傳，
	 *  而 token 只該在使用者主動要求時出現一次。
	 */
	mcpConfig: () => typedError<string | null, Failure>(__TAURI_INVOKE("mcp_config")),
	/**
	 *  改 AI 助手的偏好：埠、要不要 token。
	 * 
	 *  端點正在跑的話會重開——埠與 token 都是啟動時決定的。
	 *  「要不要自動啟用」不在這裡，它由開關自己寫。
	 */
	setMcpConfig: (port: number | null, requireToken: boolean) => typedError<McpStatus, Failure>(__TAURI_INVOKE("set_mcp_config", { port, requireToken })),
	/**  換一組新的 token。舊的立刻失效。 */
	regenerateMcpToken: () => typedError<McpStatus, Failure>(__TAURI_INVOKE("regenerate_mcp_token")),
	/**
	 *  把 lint 面板上「照著修法填的那一格」變成一次修改。
	 * 
	 *  前端送回來的是**發現本身 + 使用者填了什麼**，不是 [`Edit`]——
	 *  「L006 的答案要寫進哪個欄位」由 `loom_core::edit::edit_for` 決定。
	 *  前端因此完全不需要知道 [`Edit`] 有哪些變體。
	 */
	applyFix: (finding: Finding_Deserialize, value: FixValue) => typedError<Snapshot_Serialize, Failure>(__TAURI_INVOKE("apply_fix", { finding, value })),
	/**
	 *  退回上一步。已經到底了就原樣回傳——這不是錯誤，
	 *  使用者多按一次 Cmd+Z 不該看到紅字。
	 */
	undo: () => typedError<Snapshot_Serialize, Failure>(__TAURI_INVOKE("undo")),
	redo: () => typedError<Snapshot_Serialize, Failure>(__TAURI_INVOKE("redo")),
};

/* Types */
/**  一次標註要用的全部材料。 */
export type Annotation = {
	/**  框可以指給誰。 */
	shapes: Target[],
	/**  線可以指給誰。 */
	connections: Target[],
	/**  猜得到的那幾個。清單很長時，這是唯一讓它跑得完的東西。 */
	guesses: Guess[],
};

/**
 *  展開之後的樣子，加上它會放在哪。
 * 
 *  # 為什麼 id 在這裡就發好
 * 
 *  跟 [`crate::connect::propose`] 同一個理由：`apply` 必須是決定性的。
 *  若 id 等到套用時才產生，預覽給使用者看的就不是他真正會拿到的東西，
 *  而復原之後重做也會得到一批不同 id 的機器。
 */
export type BatchPlan = BatchPlan_Serialize | BatchPlan_Deserialize;

/**
 *  展開之後的樣子，加上它會放在哪。
 * 
 *  # 為什麼 id 在這裡就發好
 * 
 *  跟 [`crate::connect::propose`] 同一個理由：`apply` 必須是決定性的。
 *  若 id 等到套用時才產生，預覽給使用者看的就不是他真正會拿到的東西，
 *  而復原之後重做也會得到一批不同 id 的機器。
 */
export type BatchPlan_Deserialize = {
	nodes: DeploymentNode_Deserialize[],
	/**  給預覽看的一行行摘要：`vm-redis-01 / redis-01 @ 10.0.1.11:6379`。 */
	preview: string[],
};

/**
 *  展開之後的樣子，加上它會放在哪。
 * 
 *  # 為什麼 id 在這裡就發好
 * 
 *  跟 [`crate::connect::propose`] 同一個理由：`apply` 必須是決定性的。
 *  若 id 等到套用時才產生，預覽給使用者看的就不是他真正會拿到的東西，
 *  而復原之後重做也會得到一批不同 id 的機器。
 */
export type BatchPlan_Serialize = {
	nodes: DeploymentNode_Serialize[],
	/**  給預覽看的一行行摘要：`vm-redis-01 / redis-01 @ 10.0.1.11:6379`。 */
	preview: string[],
};

/**
 *  一次批次建立的規格。
 * 
 *  數字用 `u32` 而不是 `usize`：它們是「要建幾台」「從幾號開始」，
 *  不是記憶體索引。而且 `usize` 匯不出 TypeScript（specta 怕 BigInt 精度）。
 */
export type BatchSpec = {
	count: number,
	/**  Instance 的名稱樣板，例如 `redis-{n}`。 */
	nameTemplate: string,
	/**  承載機器的名稱樣板，例如 `vm-redis-{n}`。 */
	nodeTemplate: string,
	/**  `{n}` 的起始值。 */
	start: number,
	/**  `{n}` 的補零寬度。`2` 會產生 `01`、`02`。 */
	pad: number,
	/**  位址樣板，例如 `10.0.1.{ip}:6379`。 */
	addressTemplate: string,
	/**  `{ip}` 的起始值。 */
	ipStart: number,
	nodeKind: NodeKind,
	container: Id,
	endpoint: EndpointPlan,
};

/**  矩陣裡的一格。 */
export type Cell = {
	relationship: Id,
	environment: Id,
	status: Status,
	/**
	 *  這條契約在這個環境被拆成幾段實際連線。
	 *  dev 直連是 1，prod 走 F5 是 2。
	 */
	segments: number,
	/**  目標端展開成幾個 Instance。萬用字元會展開成一整群。 */
	targets: number,
	/**  目標端註明的期望數量。`None` 代表沒用萬用字元，或用了卻沒註明。 */
	expect: number | null,
	/**  這格對應到哪些 lint 規則。畫面上點下去就能跳到 lint 面板。 */
	rules: Rule[],
};

export type Change = {
	kind: ChangeKind,
	element: Element,
	/**  人看得懂的位置，例如 `prod / redis-01`。 */
	label: string,
	/**  更新前的值。新增時是 `None`。 */
	before: string | null,
	after: string,
};

export type ChangeKind = "added" | "updated";

/**  這個環境裡，連線可以接上去的一個地方。 */
export type Choice = Choice_Serialize | Choice_Deserialize;

/**  這個環境裡，連線可以接上去的一個地方。 */
export type Choice_Deserialize = {
	kind: SideKind,
	/**  「redis-01 : client-port」 */
	label: string,
	/**  下拉選單分組用：「服務」「服務（整群）」「設備」「外部系統」「人」。 */
	group: string,
	/**
	 *  直接可以塞進 [`crate::edit::Edit::AddConnection`] 的東西。
	 * 
	 *  前端**把它當不透明值原樣帶回來**，不需要看懂裡面是什麼。
	 *  這是「規則在 Rust」的同一條線：哪些東西接得上、接上去長什麼樣，
	 *  是模型知識，不是畫面知識。
	 */
	endpointing: Endpointing_Deserialize,
};

/**  這個環境裡，連線可以接上去的一個地方。 */
export type Choice_Serialize = {
	kind: SideKind,
	/**  「redis-01 : client-port」 */
	label: string,
	/**  下拉選單分組用：「服務」「服務（整群）」「設備」「外部系統」「人」。 */
	group: string,
	/**
	 *  直接可以塞進 [`crate::edit::Edit::AddConnection`] 的東西。
	 * 
	 *  前端**把它當不透明值原樣帶回來**，不需要看懂裡面是什麼。
	 *  這是「規則在 Rust」的同一條線：哪些東西接得上、接上去長什麼樣，
	 *  是模型知識，不是畫面知識。
	 */
	endpointing: Endpointing_Serialize,
};

/**
 *  環境層的一條實際連線。
 * 
 *  `serves` 指向它所服務的邏輯 [`Relationship`](crate::logical::Relationship)。
 *  Lint 把貼同一個 `serves` 的連線攤開成一張圖，檢查從來源走不走得到目標。
 */
export type Connection = Connection_Serialize | Connection_Deserialize;

/**
 *  連線的哪一端。
 * 
 *  # 為什麼需要指名
 * 
 *  一條連線的兩端**都可能是萬用字元**（`apigw-* → common-*`），
 *  所以「這條連線的期望數量不對」是個不完整的說法——它沒說是哪一端。
 *  Lint 的發現、以及照著發現去修的那次編輯，都必須指名，
 *  否則就得用猜的，而猜錯會安靜地改到另一端。
 * 
 *  名字不叫 `Side`，是為了不跟 [`crate::table::Side`]（表格上一端的完整樣貌）
 *  撞名——型別匯出到 TypeScript 之後是同一個命名空間，撞了就產不出來。
 */
export type ConnectionEnd = "from" | "to";

/**  連線是正常路徑還是備援路徑。 */
export type ConnectionKind = 
/**  平常就在走的路。預設。 */
"primary" | 
/**
 *  只在故障時才走。**它一樣要被建立、防火牆一樣要開**——
 *  所以 lint 對它的要求跟正常路徑完全相同，差別只在畫面上的呈現。
 */
"fallback";

/**
 *  環境層的一條實際連線。
 * 
 *  `serves` 指向它所服務的邏輯 [`Relationship`](crate::logical::Relationship)。
 *  Lint 把貼同一個 `serves` 的連線攤開成一張圖，檢查從來源走不走得到目標。
 */
export type Connection_Deserialize = {
	id: Id,
	serves: Id,
	/**  用途說明。空白會觸發 L007。 */
	purpose: string,
	/**
	 *  這是平常走的路，還是只在故障時走的。
	 * 
	 *  「同中心優先、某中心出問題才交叉」這種安排會讓一條契約長出四條連線，
	 *  其中兩條是備援。沒有這個欄位的話四條看起來一樣重，圖上會很吵，
	 *  讀的人也分不出平常的資料流是哪幾條。
	 */
	kind?: ConnectionKind,
	from: Endpointing_Deserialize,
	to: Endpointing_Deserialize,
	/**
	 *  使用者的備註。見 [`crate::memo_is_empty`]。
	 * 
	 *  跟 `purpose` 分開的理由同
	 *  [`Relationship::memo`](crate::logical::Relationship::memo)。
	 */
	memo?: string,
};

/**
 *  環境層的一條實際連線。
 * 
 *  `serves` 指向它所服務的邏輯 [`Relationship`](crate::logical::Relationship)。
 *  Lint 把貼同一個 `serves` 的連線攤開成一張圖，檢查從來源走不走得到目標。
 */
export type Connection_Serialize = {
	id: Id,
	serves: Id,
	/**  用途說明。空白會觸發 L007。 */
	purpose: string,
	/**
	 *  這是平常走的路，還是只在故障時走的。
	 * 
	 *  「同中心優先、某中心出問題才交叉」這種安排會讓一條契約長出四條連線，
	 *  其中兩條是備援。沒有這個欄位的話四條看起來一樣重，圖上會很吵，
	 *  讀的人也分不出平常的資料流是哪幾條。
	 */
	kind?: ConnectionKind,
	from: Endpointing_Serialize,
	to: Endpointing_Serialize,
	/**
	 *  使用者的備註。見 [`crate::memo_is_empty`]。
	 * 
	 *  跟 `purpose` 分開的理由同
	 *  [`Relationship::memo`](crate::logical::Relationship::memo)。
	 */
	memo?: string,
};

/**  一個會跑的服務：Redis、Consul、訂單 API。C4 的 `Container`。 */
export type Container = Container_Serialize | Container_Deserialize;

/**
 *  邏輯 Container 在此環境的一份服務實體。C4 的 `Container Instance`。
 * 
 *  叢集就是多個 Instance：12 台 VM 各跑一個 Redis process
 *  就是 12 個 `ContainerInstance`。節點數不另外存數字，避免兩份資料不一致。
 */
export type ContainerInstance = ContainerInstance_Serialize | ContainerInstance_Deserialize;

/**
 *  邏輯 Container 在此環境的一份服務實體。C4 的 `Container Instance`。
 * 
 *  叢集就是多個 Instance：12 台 VM 各跑一個 Redis process
 *  就是 12 個 `ContainerInstance`。節點數不另外存數字，避免兩份資料不一致。
 */
export type ContainerInstance_Deserialize = {
	id: Id,
	slug: string,
	container: Id,
	endpoints?: Endpoint_Deserialize[],
	/**
	 *  標記「刻意獨立」，關閉 L008（沒被任何連線碰到）的警告。
	 *  冷備機是合法情境，但預設應該要叫。
	 */
	standalone?: boolean,
	/**  使用者的備註。見 [`crate::memo_is_empty`]。 */
	memo?: string,
};

/**
 *  邏輯 Container 在此環境的一份服務實體。C4 的 `Container Instance`。
 * 
 *  叢集就是多個 Instance：12 台 VM 各跑一個 Redis process
 *  就是 12 個 `ContainerInstance`。節點數不另外存數字，避免兩份資料不一致。
 */
export type ContainerInstance_Serialize = {
	id: Id,
	slug: string,
	container: Id,
	endpoints?: Endpoint_Serialize[],
	/**
	 *  標記「刻意獨立」，關閉 L008（沒被任何連線碰到）的警告。
	 *  冷備機是合法情境，但預設應該要叫。
	 */
	standalone?: boolean,
	/**  使用者的備註。見 [`crate::memo_is_empty`]。 */
	memo?: string,
};

/**  一個會跑的服務：Redis、Consul、訂單 API。C4 的 `Container`。 */
export type Container_Deserialize = {
	id: Id,
	slug: string,
	name: string,
	system: Id,
	endpoints?: EndpointDef_Deserialize[],
	/**  使用者的備註。見 [`crate::memo_is_empty`]。 */
	memo?: string,
};

/**  一個會跑的服務：Redis、Consul、訂單 API。C4 的 `Container`。 */
export type Container_Serialize = {
	id: Id,
	slug: string,
	name: string,
	system: Id,
	endpoints?: EndpointDef_Serialize[],
	/**  使用者的備註。見 [`crate::memo_is_empty`]。 */
	memo?: string,
};

/**
 *  這個環境裡有哪些契約可以勾，附上它現在有沒有問題。
 * 
 *  「哪些契約在這個環境有連線」要走一次 `serves` 分組，是模型知識。
 */
export type Contract = {
	relationship: Id,
	label: string,
	/**  這個環境裡屬於它的連線數。0 表示契約在這裡沒被實現（L001 會叫）。 */
	connections: number,
	/**  這幾條連線裡有沒有 lint 叫過。 */
	problems: boolean,
};

/**  機器：實體機、VM、Linux container。C4 的 `Deployment Node`，可巢狀。 */
export type DeploymentNode = DeploymentNode_Serialize | DeploymentNode_Deserialize;

/**  機器：實體機、VM、Linux container。C4 的 `Deployment Node`，可巢狀。 */
export type DeploymentNode_Deserialize = {
	id: Id,
	slug: string,
	kind: NodeKind,
	/**  巢狀：機房 → 機器 → 容器。 */
	children?: DeploymentNode_Deserialize[],
	instances?: ContainerInstance_Deserialize[],
	/**  使用者的備註。見 [`crate::memo_is_empty`]。 */
	memo?: string,
};

/**  機器：實體機、VM、Linux container。C4 的 `Deployment Node`，可巢狀。 */
export type DeploymentNode_Serialize = {
	id: Id,
	slug: string,
	kind: NodeKind,
	/**  巢狀：機房 → 機器 → 容器。 */
	children?: DeploymentNode_Serialize[],
	instances?: ContainerInstance_Serialize[],
	/**  使用者的備註。見 [`crate::memo_is_empty`]。 */
	memo?: string,
};

/**  給畫面看的一張圖。 */
export type DiagramInfo = {
	name: string,
	/**  是不是 App 產的那一張。畫面要標出來：它會被重畫整份蓋掉。 */
	generated: boolean,
	/**  存檔之後模型又變了。這張圖畫的是舊的。 */
	stale: boolean,
};

/**
 *  這個環境有哪些圖，以及模型現在的指紋。
 * 
 *  兩件事一次給：分開問的話，畫面會有一瞬間拿舊的指紋配新的清單，
 *  而那個指紋正是「這張圖存不存得下去」的依據。
 */
export type DiagramsView = {
	diagrams: DiagramInfo[],
	/**  模型現在長什麼樣。畫面重畫之後拿它當新的 `drawnFrom`。 */
	model: string,
	/**
	 *  App 自動產生的那張圖叫什麼。
	 * 
	 *  從這裡給，前端就不必自己抄一份名字——抄了就會有兩個「保留字」，
	 *  而改名的那天只會有一邊跟著改。
	 */
	details: string,
};

/**  對專案的一次修改。 */
export type Edit = Edit_Serialize | Edit_Deserialize;

/**  對專案的一次修改。 */
export type Edit_Deserialize = 
/**
 *  L006 的修法：補上某個 Endpoint 的實際位址。
 * 
 *  Endpoint 可能掛在 Instance、設備或外部系統實體上，所以只給 id，
 *  由 [`apply`] 自己找。前端不需要知道它住在哪一層。
 */
({ setAddress: {
	environment: Id,
	endpoint: Id,
	/**
	 *  `None` 表示清空。清空是合法操作——它會讓 L006 重新叫，
	 *  那正是「我還不知道位址」該有的狀態。
	 */
	address: string | null,
} }) & { addConnection?: never; addInstances?: never; addResource?: never; batch?: never; deleteConnection?: never; deleteResource?: never; setConnectionKind?: never; setExpect?: never; setPurpose?: never; setStandalone?: never; updateResource?: never } | 
/**
 *  L007 的修法：填上用途。
 * 
 *  `environment` 為 `None` 時指的是邏輯層的 Relationship。
 */
({ setPurpose: {
	environment: Id | null,
	subject: Id,
	purpose: string,
} }) & { addConnection?: never; addInstances?: never; addResource?: never; batch?: never; deleteConnection?: never; deleteResource?: never; setAddress?: never; setConnectionKind?: never; setExpect?: never; setStandalone?: never; updateResource?: never } | 
/**  L004 / L005 的修法：萬用字元的期望數量。 */
({ setExpect: {
	environment: Id,
	connection: Id,
	side: ConnectionEnd,
	expect: number | null,
} }) & { addConnection?: never; addInstances?: never; addResource?: never; batch?: never; deleteConnection?: never; deleteResource?: never; setAddress?: never; setConnectionKind?: never; setPurpose?: never; setStandalone?: never; updateResource?: never } | 
/**  L008 的修法：標記「刻意獨立」，例如冷備機。 */
({ setStandalone: {
	environment: Id,
	/**  Instance 或外部系統實體的 id。 */
	subject: Id,
	standalone: boolean,
} }) & { addConnection?: never; addInstances?: never; addResource?: never; batch?: never; deleteConnection?: never; deleteResource?: never; setAddress?: never; setConnectionKind?: never; setExpect?: never; setPurpose?: never; updateResource?: never } | 
/**  改成正常路徑或備援路徑。 */
({ setConnectionKind: {
	environment: Id,
	connection: Id,
	kind: ConnectionKind,
} }) & { addConnection?: never; addInstances?: never; addResource?: never; batch?: never; deleteConnection?: never; deleteResource?: never; setAddress?: never; setExpect?: never; setPurpose?: never; setStandalone?: never; updateResource?: never } | 
/**
 *  L001／L002 的修法：新增一條環境層連線。
 * 
 *  `id` 由 [`crate::connect::propose`] 先發好，不是在這裡產生——
 *  這樣 `apply` 是決定性的：預覽算出來的就是套用後真正的樣子，
 *  復原重做也會重播出同一條連線，而不是每次換一個 UUID。
 * 
 *  兩端是完整的 [`Endpointing`]，由 [`crate::connect::choices`] 提供，
 *  前端當不透明值原樣帶回來。
 */
({ addConnection: {
	environment: Id,
	id: Id,
	serves: Id,
	purpose: string,
	kind: ConnectionKind,
	from: Endpointing_Deserialize,
	to: Endpointing_Deserialize,
} }) & { addInstances?: never; addResource?: never; batch?: never; deleteConnection?: never; deleteResource?: never; setAddress?: never; setConnectionKind?: never; setExpect?: never; setPurpose?: never; setStandalone?: never; updateResource?: never } | 
/**
 *  批次建立機器與服務實體：L001「這個服務一台都還沒建」的修法。
 * 
 *  `nodes` 是 [`crate::batch::plan`] 展開好的（id 也發好了），
 *  這一層只負責掛上去。理由同 [`Edit::AddConnection`]：`apply` 要是決定性的。
 */
({ addInstances: {
	environment: Id,
	/**  掛在哪個部署節點底下（通常是站點）。`None` 表示掛在環境最上層。 */
	within: Id | null,
	nodes: DeploymentNode_Deserialize[],
} }) & { addConnection?: never; addResource?: never; batch?: never; deleteConnection?: never; deleteResource?: never; setAddress?: never; setConnectionKind?: never; setExpect?: never; setPurpose?: never; setStandalone?: never; updateResource?: never } | 
/**
 *  刪掉一條環境層連線。
 * 
 *  刪除一定要先看 [`preview`]——少一條連線正是本工具存在要抓的東西。
 */
({ deleteConnection: {
	environment: Id,
	connection: Id,
} }) & { addConnection?: never; addInstances?: never; addResource?: never; batch?: never; deleteResource?: never; setAddress?: never; setConnectionKind?: never; setExpect?: never; setPurpose?: never; setStandalone?: never; updateResource?: never } | 
/**  新增一個模型元素。id 由 [`crate::resource::blank`] 先發好。 */
({ addResource: Resource_Deserialize }) & { addConnection?: never; addInstances?: never; batch?: never; deleteConnection?: never; deleteResource?: never; setAddress?: never; setConnectionKind?: never; setExpect?: never; setPurpose?: never; setStandalone?: never; updateResource?: never } | 
/**
 *  整份換掉一個模型元素。
 * 
 *  帶完整的值而不是欄位差異：整份換掉的語意最單純，
 *  而復原本來就是存整份快照，省不了什麼。
 */
({ updateResource: Resource_Deserialize }) & { addConnection?: never; addInstances?: never; addResource?: never; batch?: never; deleteConnection?: never; deleteResource?: never; setAddress?: never; setConnectionKind?: never; setExpect?: never; setPurpose?: never; setStandalone?: never } | 
/**
 *  刪掉一個模型元素。
 * 
 *  **不連帶刪除。** 指著它的東西會變成懸空，由 L012 叫出來
 *  （見 `docs/decisions.md`）。連帶刪除可能一次消失幾十個東西，
 *  而這工具的重點就是「怕漏」。
 * 
 *  想連帶刪除的話走 [`crate::cascade`]：它把「還會壞掉哪些」算成
 *  一串 `Edit`，包成一個 [`Edit::Batch`]，**先給人看過**再送進來。
 */
({ deleteResource: Resource_Deserialize }) & { addConnection?: never; addInstances?: never; addResource?: never; batch?: never; deleteConnection?: never; setAddress?: never; setConnectionKind?: never; setExpect?: never; setPurpose?: never; setStandalone?: never; updateResource?: never } | 
/**
 *  一整批修改，算**一步**。
 * 
 *  # 為什麼需要它
 * 
 *  從一份盤點資料建模型是幾百次新增。一次一個 `Edit` 有三個代價，
 *  每一個都是真的痛：
 * 
 *  - **復原變成按幾百次。** 而「Agent 建了一批、人看過覺得不對」
 *    正是最需要一鍵退回的時候。
 *  - **每一步都要重算一次 lint。** 幾百條連線的專案上這是平方級的浪費。
 *  - **MCP 那邊是幾百趟來回。** 慢的是趟數，不是每趟做的事。
 * 
 *  # 全成功才算數
 * 
 *  中途失敗**整批不算**，跟 [`Edit::AddInstances`] 同一個規矩。
 *  「建了一半」是最糟的結果：看起來成功了，其實模型是殘的，
 *  而殘在哪裡沒有人知道。
 * 
 *  巢狀是允許的，不特別處理——遞迴下去語意剛好對。
 */
({ batch: Edit_Deserialize[] }) & { addConnection?: never; addInstances?: never; addResource?: never; deleteConnection?: never; deleteResource?: never; setAddress?: never; setConnectionKind?: never; setExpect?: never; setPurpose?: never; setStandalone?: never; updateResource?: never };

/**  對專案的一次修改。 */
export type Edit_Serialize = 
/**
 *  L006 的修法：補上某個 Endpoint 的實際位址。
 * 
 *  Endpoint 可能掛在 Instance、設備或外部系統實體上，所以只給 id，
 *  由 [`apply`] 自己找。前端不需要知道它住在哪一層。
 */
({ setAddress: {
	environment: Id,
	endpoint: Id,
	/**
	 *  `None` 表示清空。清空是合法操作——它會讓 L006 重新叫，
	 *  那正是「我還不知道位址」該有的狀態。
	 */
	address: string | null,
} }) & { addConnection?: never; addInstances?: never; addResource?: never; batch?: never; deleteConnection?: never; deleteResource?: never; setConnectionKind?: never; setExpect?: never; setPurpose?: never; setStandalone?: never; updateResource?: never } | 
/**
 *  L007 的修法：填上用途。
 * 
 *  `environment` 為 `None` 時指的是邏輯層的 Relationship。
 */
({ setPurpose: {
	environment: Id | null,
	subject: Id,
	purpose: string,
} }) & { addConnection?: never; addInstances?: never; addResource?: never; batch?: never; deleteConnection?: never; deleteResource?: never; setAddress?: never; setConnectionKind?: never; setExpect?: never; setStandalone?: never; updateResource?: never } | 
/**  L004 / L005 的修法：萬用字元的期望數量。 */
({ setExpect: {
	environment: Id,
	connection: Id,
	side: ConnectionEnd,
	expect: number | null,
} }) & { addConnection?: never; addInstances?: never; addResource?: never; batch?: never; deleteConnection?: never; deleteResource?: never; setAddress?: never; setConnectionKind?: never; setPurpose?: never; setStandalone?: never; updateResource?: never } | 
/**  L008 的修法：標記「刻意獨立」，例如冷備機。 */
({ setStandalone: {
	environment: Id,
	/**  Instance 或外部系統實體的 id。 */
	subject: Id,
	standalone: boolean,
} }) & { addConnection?: never; addInstances?: never; addResource?: never; batch?: never; deleteConnection?: never; deleteResource?: never; setAddress?: never; setConnectionKind?: never; setExpect?: never; setPurpose?: never; updateResource?: never } | 
/**  改成正常路徑或備援路徑。 */
({ setConnectionKind: {
	environment: Id,
	connection: Id,
	kind: ConnectionKind,
} }) & { addConnection?: never; addInstances?: never; addResource?: never; batch?: never; deleteConnection?: never; deleteResource?: never; setAddress?: never; setExpect?: never; setPurpose?: never; setStandalone?: never; updateResource?: never } | 
/**
 *  L001／L002 的修法：新增一條環境層連線。
 * 
 *  `id` 由 [`crate::connect::propose`] 先發好，不是在這裡產生——
 *  這樣 `apply` 是決定性的：預覽算出來的就是套用後真正的樣子，
 *  復原重做也會重播出同一條連線，而不是每次換一個 UUID。
 * 
 *  兩端是完整的 [`Endpointing`]，由 [`crate::connect::choices`] 提供，
 *  前端當不透明值原樣帶回來。
 */
({ addConnection: {
	environment: Id,
	id: Id,
	serves: Id,
	purpose: string,
	kind: ConnectionKind,
	from: Endpointing_Serialize,
	to: Endpointing_Serialize,
} }) & { addInstances?: never; addResource?: never; batch?: never; deleteConnection?: never; deleteResource?: never; setAddress?: never; setConnectionKind?: never; setExpect?: never; setPurpose?: never; setStandalone?: never; updateResource?: never } | 
/**
 *  批次建立機器與服務實體：L001「這個服務一台都還沒建」的修法。
 * 
 *  `nodes` 是 [`crate::batch::plan`] 展開好的（id 也發好了），
 *  這一層只負責掛上去。理由同 [`Edit::AddConnection`]：`apply` 要是決定性的。
 */
({ addInstances: {
	environment: Id,
	/**  掛在哪個部署節點底下（通常是站點）。`None` 表示掛在環境最上層。 */
	within: Id | null,
	nodes: DeploymentNode_Serialize[],
} }) & { addConnection?: never; addResource?: never; batch?: never; deleteConnection?: never; deleteResource?: never; setAddress?: never; setConnectionKind?: never; setExpect?: never; setPurpose?: never; setStandalone?: never; updateResource?: never } | 
/**
 *  刪掉一條環境層連線。
 * 
 *  刪除一定要先看 [`preview`]——少一條連線正是本工具存在要抓的東西。
 */
({ deleteConnection: {
	environment: Id,
	connection: Id,
} }) & { addConnection?: never; addInstances?: never; addResource?: never; batch?: never; deleteResource?: never; setAddress?: never; setConnectionKind?: never; setExpect?: never; setPurpose?: never; setStandalone?: never; updateResource?: never } | 
/**  新增一個模型元素。id 由 [`crate::resource::blank`] 先發好。 */
({ addResource: Resource_Serialize }) & { addConnection?: never; addInstances?: never; batch?: never; deleteConnection?: never; deleteResource?: never; setAddress?: never; setConnectionKind?: never; setExpect?: never; setPurpose?: never; setStandalone?: never; updateResource?: never } | 
/**
 *  整份換掉一個模型元素。
 * 
 *  帶完整的值而不是欄位差異：整份換掉的語意最單純，
 *  而復原本來就是存整份快照，省不了什麼。
 */
({ updateResource: Resource_Serialize }) & { addConnection?: never; addInstances?: never; addResource?: never; batch?: never; deleteConnection?: never; deleteResource?: never; setAddress?: never; setConnectionKind?: never; setExpect?: never; setPurpose?: never; setStandalone?: never } | 
/**
 *  刪掉一個模型元素。
 * 
 *  **不連帶刪除。** 指著它的東西會變成懸空，由 L012 叫出來
 *  （見 `docs/decisions.md`）。連帶刪除可能一次消失幾十個東西，
 *  而這工具的重點就是「怕漏」。
 * 
 *  想連帶刪除的話走 [`crate::cascade`]：它把「還會壞掉哪些」算成
 *  一串 `Edit`，包成一個 [`Edit::Batch`]，**先給人看過**再送進來。
 */
({ deleteResource: Resource_Serialize }) & { addConnection?: never; addInstances?: never; addResource?: never; batch?: never; deleteConnection?: never; setAddress?: never; setConnectionKind?: never; setExpect?: never; setPurpose?: never; setStandalone?: never; updateResource?: never } | 
/**
 *  一整批修改，算**一步**。
 * 
 *  # 為什麼需要它
 * 
 *  從一份盤點資料建模型是幾百次新增。一次一個 `Edit` 有三個代價，
 *  每一個都是真的痛：
 * 
 *  - **復原變成按幾百次。** 而「Agent 建了一批、人看過覺得不對」
 *    正是最需要一鍵退回的時候。
 *  - **每一步都要重算一次 lint。** 幾百條連線的專案上這是平方級的浪費。
 *  - **MCP 那邊是幾百趟來回。** 慢的是趟數，不是每趟做的事。
 * 
 *  # 全成功才算數
 * 
 *  中途失敗**整批不算**，跟 [`Edit::AddInstances`] 同一個規矩。
 *  「建了一半」是最糟的結果：看起來成功了，其實模型是殘的，
 *  而殘在哪裡沒有人知道。
 * 
 *  巢狀是允許的，不特別處理——遞迴下去語意剛好對。
 */
({ batch: Edit_Serialize[] }) & { addConnection?: never; addInstances?: never; addResource?: never; deleteConnection?: never; deleteResource?: never; setAddress?: never; setConnectionKind?: never; setExpect?: never; setPurpose?: never; setStandalone?: never; updateResource?: never };

/**  動到的是什麼東西。畫面上用來分組。 */
export type Element = "environment" | 
/**  邏輯層的服務。 */
"container" | 
/**  邏輯層的接點定義。 */
"endpointDef" | 
/**  邏輯層的連線契約。 */
"relationship" | "deploymentNode" | "containerInstance" | 
/**  某個 Endpoint 的實際位址。 */
"address" | "infrastructureNode" | "softwareSystemInstance" | "connection";

/**  模型裡的元素是什麼東西。只用於顯示與「要不要建到模型裡」的提示。 */
export type ElementKind = "deployment-node" | "container-instance" | "infrastructure-node" | "software-system-instance" | "connection";

/**  Endpoint 在某環境的實際樣貌：定義加上位址。 */
export type Endpoint = Endpoint_Serialize | Endpoint_Deserialize;

/**
 *  Endpoint 的定義：只有名字與協定，沒有位址。
 * 
 *  位址屬於環境層的 [`Endpoint`](crate::environment::Endpoint)。
 */
export type EndpointDef = EndpointDef_Serialize | EndpointDef_Deserialize;

/**
 *  Endpoint 的定義：只有名字與協定，沒有位址。
 * 
 *  位址屬於環境層的 [`Endpoint`](crate::environment::Endpoint)。
 */
export type EndpointDef_Deserialize = {
	id: Id,
	slug: string,
	protocol: Protocol,
	/**  使用者的備註。見 [`crate::memo_is_empty`]。 */
	memo?: string,
};

/**
 *  Endpoint 的定義：只有名字與協定，沒有位址。
 * 
 *  位址屬於環境層的 [`Endpoint`](crate::environment::Endpoint)。
 */
export type EndpointDef_Serialize = {
	id: Id,
	slug: string,
	protocol: Protocol,
	/**  使用者的備註。見 [`crate::memo_is_empty`]。 */
	memo?: string,
};

/**  要在每個 Instance 上建立的 Endpoint。 */
export type EndpointPlan = {
	/**  對應邏輯層的 `EndpointDef`。 */
	def: Id,
	slug: string,
	protocol: Protocol,
};

/**  Endpoint 在某環境的實際樣貌：定義加上位址。 */
export type Endpoint_Deserialize = {
	id: Id,
	slug: string,
	/**
	 *  對應邏輯層的 `EndpointDef`。
	 *  [`InfrastructureNode`] 的 endpoint 沒有邏輯層對應，此處為 `None`。
	 */
	def?: Id | null,
	protocol: Protocol,
	/**
	 *  `10.0.1.11:6379` / JDBC URL / socket 路徑 / 檔案路徑。
	 *  缺少會觸發 L006，所以必須允許 `None`。
	 */
	address: string | null,
	/**  使用者的備註。見 [`crate::memo_is_empty`]。 */
	memo?: string,
};

/**  Endpoint 在某環境的實際樣貌：定義加上位址。 */
export type Endpoint_Serialize = {
	id: Id,
	slug: string,
	/**
	 *  對應邏輯層的 `EndpointDef`。
	 *  [`InfrastructureNode`] 的 endpoint 沒有邏輯層對應，此處為 `None`。
	 */
	def?: Id | null,
	protocol: Protocol,
	/**
	 *  `10.0.1.11:6379` / JDBC URL / socket 路徑 / 檔案路徑。
	 *  缺少會觸發 L006，所以必須允許 `None`。
	 */
	address: string | null,
	/**  使用者的備註。見 [`crate::memo_is_empty`]。 */
	memo?: string,
};

/**
 *  連線的一端。
 * 
 *  YAML 上長這樣（`serves` 相同的連線串起來就是一條路徑）：
 * 
 *  ```yaml
 *  from:
 *    instance:
 *      target: { one: i-prod-api-01 }   # 來源不填 endpoint = OS 分配
 *  to:
 *    infra:
 *      node: f5-prod
 *      endpoint: ep-f5-redis
 *  ```
 */
export type Endpointing = Endpointing_Serialize | Endpointing_Deserialize;

/**
 *  連線的一端。
 * 
 *  YAML 上長這樣（`serves` 相同的連線串起來就是一條路徑）：
 * 
 *  ```yaml
 *  from:
 *    instance:
 *      target: { one: i-prod-api-01 }   # 來源不填 endpoint = OS 分配
 *  to:
 *    infra:
 *      node: f5-prod
 *      endpoint: ep-f5-redis
 *  ```
 */
export type Endpointing_Deserialize = ({ instance: {
	/**
	 *  欄位叫 `target` 而不是 `instance`，否則 YAML 會出現
	 *  `instance: { instance: ... }` 這種讀不下去的巢狀。
	 */
	target: InstanceRef_Deserialize,
	/**
	 *  指向**邏輯層的 [`EndpointDef`](crate::logical::EndpointDef)**，
	 *  不是某一台的具體 [`Endpoint`]。
	 * 
	 *  因為萬用字元會展開成多台 Instance，各有各的具體 endpoint；
	 *  只有邏輯層的定義才是它們共通的東西。實際位址由各 Instance
	 *  上 `def` 對應的那個 endpoint 提供。
	 * 
	 *  來源端可為 `None`，表示由作業系統分配（ephemeral port）。
	 */
	endpoint?: Id | null,
} }) & { infra?: never; person?: never; system?: never } | ({ infra: {
	node: Id,
	/**
	 *  指向該設備上的具體 [`Endpoint`] id。
	 * 
	 *  與 Instance 端不對稱是刻意的：設備不對應任何邏輯層元素，
	 *  它的 endpoint（VIP 位址）沒有 `EndpointDef` 可以指。
	 */
	endpoint?: Id | null,
} }) & { instance?: never; person?: never; system?: never } | 
/**  外部系統。不支援萬用字元——一個外部系統在一個環境就是一個實體。 */
({ system: {
	instance: Id,
	/**
	 *  同 Instance 端，指向邏輯層的 `EndpointDef`（掛在
	 *  [`SoftwareSystem`](crate::logical::SoftwareSystem) 上）。
	 */
	endpoint?: Id | null,
} }) & { infra?: never; instance?: never; person?: never } | 
/**
 *  真人。只會出現在**來源端**——使用者是流量的起點。
 * 
 *  人沒有實體也沒有位址，所以這一端只指向邏輯層的
 *  [`Person`](crate::logical::Person)，沒有 endpoint。
 *  「使用者從哪裡連過來」不是我們配置得到的東西。
 */
({ person: {
	person: Id,
} }) & { infra?: never; instance?: never; system?: never };

/**
 *  連線的一端。
 * 
 *  YAML 上長這樣（`serves` 相同的連線串起來就是一條路徑）：
 * 
 *  ```yaml
 *  from:
 *    instance:
 *      target: { one: i-prod-api-01 }   # 來源不填 endpoint = OS 分配
 *  to:
 *    infra:
 *      node: f5-prod
 *      endpoint: ep-f5-redis
 *  ```
 */
export type Endpointing_Serialize = ({ instance: {
	/**
	 *  欄位叫 `target` 而不是 `instance`，否則 YAML 會出現
	 *  `instance: { instance: ... }` 這種讀不下去的巢狀。
	 */
	target: InstanceRef_Serialize,
	/**
	 *  指向**邏輯層的 [`EndpointDef`](crate::logical::EndpointDef)**，
	 *  不是某一台的具體 [`Endpoint`]。
	 * 
	 *  因為萬用字元會展開成多台 Instance，各有各的具體 endpoint；
	 *  只有邏輯層的定義才是它們共通的東西。實際位址由各 Instance
	 *  上 `def` 對應的那個 endpoint 提供。
	 * 
	 *  來源端可為 `None`，表示由作業系統分配（ephemeral port）。
	 */
	endpoint?: Id | null,
} }) & { infra?: never; person?: never; system?: never } | ({ infra: {
	node: Id,
	/**
	 *  指向該設備上的具體 [`Endpoint`] id。
	 * 
	 *  與 Instance 端不對稱是刻意的：設備不對應任何邏輯層元素，
	 *  它的 endpoint（VIP 位址）沒有 `EndpointDef` 可以指。
	 */
	endpoint?: Id | null,
} }) & { instance?: never; person?: never; system?: never } | 
/**  外部系統。不支援萬用字元——一個外部系統在一個環境就是一個實體。 */
({ system: {
	instance: Id,
	/**
	 *  同 Instance 端，指向邏輯層的 `EndpointDef`（掛在
	 *  [`SoftwareSystem`](crate::logical::SoftwareSystem) 上）。
	 */
	endpoint?: Id | null,
} }) & { infra?: never; instance?: never; person?: never } | 
/**
 *  真人。只會出現在**來源端**——使用者是流量的起點。
 * 
 *  人沒有實體也沒有位址，所以這一端只指向邏輯層的
 *  [`Person`](crate::logical::Person)，沒有 endpoint。
 *  「使用者從哪裡連過來」不是我們配置得到的東西。
 */
({ person: {
	person: Id,
} }) & { infra?: never; instance?: never; system?: never };

/**  一個部署環境。 */
export type Environment = Environment_Serialize | Environment_Deserialize;

/**  一個部署環境。 */
export type Environment_Deserialize = {
	id: Id,
	slug: string,
	name: string,
	nodes?: DeploymentNode_Deserialize[],
	infra?: InfrastructureNode_Deserialize[],
	/**  外部系統在此環境的實體。不在 `nodes` 底下，因為那些機器不是我們的。 */
	systems?: SoftwareSystemInstance_Deserialize[],
	connections?: Connection_Deserialize[],
	/**  使用者的備註。見 [`crate::memo_is_empty`]。 */
	memo?: string,
};

/**  一個部署環境。 */
export type Environment_Serialize = {
	id: Id,
	slug: string,
	name: string,
	nodes?: DeploymentNode_Serialize[],
	infra?: InfrastructureNode_Serialize[],
	/**  外部系統在此環境的實體。不在 `nodes` 底下，因為那些機器不是我們的。 */
	systems?: SoftwareSystemInstance_Serialize[],
	connections?: Connection_Serialize[],
	/**  使用者的備註。見 [`crate::memo_is_empty`]。 */
	memo?: string,
};

/**
 *  前端拿到的錯誤。
 * 
 *  只是字串——使用者需要的是「哪裡出錯、怎麼修」，不是錯誤型別的階層。
 */
export type Failure = {
	message: string,
};

/**
 *  一項發現。
 * 
 *  欄位順序即排序順序，讓 lint 的輸出穩定可比對。
 */
export type Finding = Finding_Serialize | Finding_Deserialize;

/**
 *  一項發現，外加它的嚴重度與修法。
 * 
 *  `Rule::severity()` 在 Rust 是一個方法，序列化不會帶過去。若讓前端自己
 *  抄一份「哪些規則算錯誤」的對照表，新增規則時那份一定會忘記更新，
 *  而且是**靜靜地**算錯數字。所以在這裡攤平成欄位。
 * 
 *  `fix` 同理：「L006 要填的是位址、L004 要填的是數字」是規則不是畫面，
 *  由 `loom_core::edit::fix_for` 決定，前端只負責照著長出控制項。
 */
export type FindingView = {
	rule: Rule,
	severity: Severity,
	environment: Id | null,
	subject: Id,
	/**
	 *  問題出在連線的哪一端。前端不需要看懂它，但**必須原樣送回來**——
	 *  兩端都是萬用字元時，少了它就分不出這一項在講哪一端。
	 */
	end: ConnectionEnd | null,
	detail: string,
	/**
	 *  這一項能不能用單一欄位修好，以及該長成什麼樣的輸入。
	 *  `None` 表示要新增／改接連線，不是填一格能解決的。
	 */
	fix: Fix | null,
};

/**
 *  一項發現。
 * 
 *  欄位順序即排序順序，讓 lint 的輸出穩定可比對。
 */
export type Finding_Deserialize = {
	rule: Rule,
	/**  發生在哪個環境；邏輯層本身的問題為 `None`。 */
	environment: Id | null,
	/**  出問題的元素。 */
	subject: Id,
	/**
	 *  問題出在連線的哪一端。
	 * 
	 *  # 為什麼不能省
	 * 
	 *  一條連線的兩端都可能是萬用字元（`apigw-* → common-*`），
	 *  於是同一條連線會產生**兩項 rule 與 subject 都相同的 L004**。
	 *  少了這個欄位，「照著發現去修」就只能猜是哪一端——
	 *  而猜錯會安靜地改到另一端，使用者按了套用卻什麼都沒發生。
	 * 
	 *  跟連線的端點無關的規則（L001／L006／L007／L008）是 `None`。
	 */
	end?: ConnectionEnd | null,
	detail: string,
};

/**
 *  一項發現。
 * 
 *  欄位順序即排序順序，讓 lint 的輸出穩定可比對。
 */
export type Finding_Serialize = {
	rule: Rule,
	/**  發生在哪個環境；邏輯層本身的問題為 `None`。 */
	environment: Id | null,
	/**  出問題的元素。 */
	subject: Id,
	/**
	 *  問題出在連線的哪一端。
	 * 
	 *  # 為什麼不能省
	 * 
	 *  一條連線的兩端都可能是萬用字元（`apigw-* → common-*`），
	 *  於是同一條連線會產生**兩項 rule 與 subject 都相同的 L004**。
	 *  少了這個欄位，「照著發現去修」就只能猜是哪一端——
	 *  而猜錯會安靜地改到另一端，使用者按了套用卻什麼都沒發生。
	 * 
	 *  跟連線的端點無關的規則（L001／L006／L007／L008）是 `None`。
	 */
	end?: ConnectionEnd | null,
	detail: string,
};

/**
 *  這項發現該用哪種控制項來修。
 * 
 *  只描述「長什麼樣的輸入」，不描述畫面細節——畫面是前端的事，
 *  但「L006 要填的是位址不是數字」是規則，屬於這裡。
 */
export type Fix = 
/**  填一段文字（位址、用途）。 */
({ text: {
	/**  欄位提示，例如「10.0.1.11:6379」。 */
	hint: string,
	current: string | null,
} }) & { addConnection?: never; addInstances?: never; addResource?: never; count?: never; manual?: never; toggle?: never } | 
/**  填一個數字（expect）。附上實際符合的數量當預設值。 */
({ count: {
	suggestion: number | null,
} }) & { addConnection?: never; addInstances?: never; addResource?: never; manual?: never; text?: never; toggle?: never } | 
/**  一個開關（standalone）。 */
({ toggle: {
	label: string,
} }) & { addConnection?: never; addInstances?: never; addResource?: never; count?: never; manual?: never; text?: never } | 
/**
 *  開一張「新增連線」的表單。**這個沒辦法在 lint 面板上填一格解決**，
 *  但它仍然是個修法——所以它有值，不是 `None`。
 * 
 *  `relationship` 是要補的那條契約，前端拿它去問 `propose_connection`。
 */
({ addConnection: {
	relationship: Id,
} }) & { addInstances?: never; addResource?: never; count?: never; manual?: never; text?: never; toggle?: never } | 
/**
 *  開一張「批次建立機器」的表單。L001 報在**服務**上時的修法——
 *  那個服務在這個環境一台都還沒建。
 */
({ addInstances: {
	container: Id,
} }) & { addConnection?: never; addResource?: never; count?: never; manual?: never; text?: never; toggle?: never } | 
/**
 *  開一張**空白資源**的表單。L001 報在**外部系統**上時的修法——
 *  那個外部系統在這個環境還沒有實體，所以也就沒有位址。
 * 
 *  # 為什麼不直接建一個
 * 
 *  它要一個名字跟一個位址，兩個都只有人知道。工具替他填一個假的，
 *  只會把「缺位址」換成「位址是錯的」——而後者不會再被 lint 叫。
 * 
 *  # 為什麼欄位剛好是這三個
 * 
 *  因為它們就是 `resource::blank` 的參數。前端拿到之後原樣轉給
 *  既有的 `blank_resource` command 就好，不必知道空白的
 *  `SoftwareSystemInstance` 長什麼樣——那是模型知識。
 */
({ addResource: {
	kind: Kind,
	environment: Id | null,
	/**  掛在誰底下。外部系統實體是它對應的那個系統。 */
	owner: Id | null,
} }) & { addConnection?: never; addInstances?: never; count?: never; manual?: never; text?: never; toggle?: never } | 
/**
 *  **沒有**可以填的一格，也沒有表單可以開——但下一步是什麼講得出來。
 * 
 *  # 為什麼這也是一種 `Fix`
 * 
 *  畫面上原本對這些發現寫死一句「要改接」。那句話是規則知識
 *  （它只對 L003／L012 成立），寫在前端就是規則漏出去了——
 *  而 L013「把兩端對調」與 L014「改一個名字」都不是改接。
 * 
 *  所以連這句話都由這裡給。前端照著印就好，一樣不必認得規則代號。
 */
({ manual: {
	hint: string,
} }) & { addConnection?: never; addInstances?: never; addResource?: never; count?: never; text?: never; toggle?: never };

/**  使用者在 [`Fix`] 的控制項裡填的東西。 */
export type FixValue = ({ text: string }) & { count?: never; toggle?: never } | ({ count: number | null }) & { text?: never; toggle?: never } | ({ toggle: boolean }) & { count?: never; text?: never };

/**
 *  使用者勾了什麼。
 * 
 *  兩個條件是 **AND**，跟連線表上「搜尋 + 只看有問題」的組合方式一致——
 *  同一個畫面裡兩種組合法會讓人算不準自己看到的是什麼。
 */
export type Focus = {
	/**
	 *  只留這幾條契約的。**空的表示不篩**，不是「一條都不要」——
	 *  空的當成全暗的話，一打開篩選面板整張圖就會先黑掉。
	 */
	relationships?: Id[],
	/**  只留 lint 有意見的。 */
	problems?: boolean,
};

/**  篩選面板需要的一切。 */
export type FocusView = {
	/**  可以勾的契約。 */
	contracts: Contract[],
	/**  照目前的勾選，誰該亮。 */
	highlight: Highlight,
	/**
	 *  這個環境總共幾個形狀。「亮了幾個 / 共幾個」的分母——
	 *  少了它，使用者不知道自己篩掉了多少，也就不知道自己在看的是一小角。
	 */
	shapes: number,
};

/**
 *  「這個框看起來就是那個元素」。
 * 
 *  只是建議，**不會自己套用**。指定要由人按下去——猜錯一個綁定，
 *  之後的對帳會拿它當事實，而使用者不會知道自己沒看過那一項。
 */
export type Guess = {
	cell: string,
	target: Id,
};

/**  該亮的東西。沒被列到的就是要調暗的。 */
export type Highlight = {
	/**  該亮的形狀。含機器與站點——見 [`highlight`] 裡祖先那一段。 */
	shapes: Id[],
	/**  該亮的線（實際連線的 id）。 */
	connections: Id[],
};

/**  元素的永久識別碼。建立後永不改變。 */
export type Id = string;

/**  [`preview`] 的結果：這次修改會弄壞什麼、會修好什麼。 */
export type Impact = Impact_Serialize | Impact_Deserialize;

/**  [`preview`] 的結果：這次修改會弄壞什麼、會修好什麼。 */
export type Impact_Deserialize = {
	/**  套用後**新冒出來**的發現。刪除確認框要顯眼地列出這些。 */
	introduced: Finding_Deserialize[],
	/**  套用後**消失**的發現。 */
	resolved: Finding_Deserialize[],
};

/**  [`preview`] 的結果：這次修改會弄壞什麼、會修好什麼。 */
export type Impact_Serialize = {
	/**  套用後**新冒出來**的發現。刪除確認框要顯眼地列出這些。 */
	introduced: Finding_Serialize[],
	/**  套用後**消失**的發現。 */
	resolved: Finding_Serialize[],
};

/**
 *  F5 等 VIP 設備。C4 的 `Infrastructure Node`。
 * 
 *  它**不含 Container**，但有自己的 endpoint（VIP 位址），
 *  因此連線可以「經過」它——這也是為什麼經過 F5 的流量會拆成兩段。
 */
export type InfrastructureNode = InfrastructureNode_Serialize | InfrastructureNode_Deserialize;

/**
 *  F5 等 VIP 設備。C4 的 `Infrastructure Node`。
 * 
 *  它**不含 Container**，但有自己的 endpoint（VIP 位址），
 *  因此連線可以「經過」它——這也是為什麼經過 F5 的流量會拆成兩段。
 */
export type InfrastructureNode_Deserialize = {
	id: Id,
	slug: string,
	endpoints?: Endpoint_Deserialize[],
	/**  使用者的備註。見 [`crate::memo_is_empty`]。 */
	memo?: string,
};

/**
 *  F5 等 VIP 設備。C4 的 `Infrastructure Node`。
 * 
 *  它**不含 Container**，但有自己的 endpoint（VIP 位址），
 *  因此連線可以「經過」它——這也是為什麼經過 F5 的流量會拆成兩段。
 */
export type InfrastructureNode_Serialize = {
	id: Id,
	slug: string,
	endpoints?: Endpoint_Serialize[],
	/**  使用者的備註。見 [`crate::memo_is_empty`]。 */
	memo?: string,
};

/**  連線一端指向的 Instance：可以是一個，也可以是一整群。 */
export type InstanceRef = InstanceRef_Serialize | InstanceRef_Deserialize;

/**  連線一端指向的 Instance：可以是一個，也可以是一整群。 */
export type InstanceRef_Deserialize = 
/**  指名一個 Instance。 */
({ one: Id }) & { pattern?: never } | 
/**
 *  萬用字元，例如 `redis-*`。
 * 
 *  `expect` 是期望數量。**它必須是 `Option`**：萬用字元表示「現在有幾台就
 *  連幾台」，少建一台 VM 會看起來完全正常，正好吃掉本工具的核心價值。
 *  因此沒填 `expect` 要能被 lint 抓出來（L005），型別就不能強制它存在。
 */
({ pattern: {
	slug_pattern: string,
	/**
	 *  只算這個 [`DeploymentNode`] 底下的（含所有子孫）。
	 * 
	 *  # 為什麼需要它
	 * 
	 *  `redis-* expect 6` 只數總量。有人把一台機器從主中心搬到異地，
	 *  總數還是 6，**lint 不會叫**——而那正是這個工具存在的理由。
	 * 
	 *  拆成兩條「主中心 3 台」「異地 3 台」就抓得到。而站點資訊
	 *  **本來就在模型裡**（Instance 住在 VM 裡，VM 住在站點裡），
	 *  所以不需要新的 Cluster 概念，只需要能限定範圍。
	 * 
	 *  順帶好處：站點不必再編進 slug（`redis-main-01`）。
	 *  名字編了資訊就會說謊——機器搬家之後 slug 不會自己改。
	 */
	within?: Id | null,
	/**
	 *  用 `u32` 而不是 `usize`：這是「期望有幾台機器」，不是記憶體索引。
	 *  而且 `usize` 不能匯出成 TypeScript（specta 怕 BigInt 精度問題）。
	 */
	expect?: number | null,
} }) & { one?: never };

/**  連線一端指向的 Instance：可以是一個，也可以是一整群。 */
export type InstanceRef_Serialize = 
/**  指名一個 Instance。 */
({ one: Id }) & { pattern?: never } | 
/**
 *  萬用字元，例如 `redis-*`。
 * 
 *  `expect` 是期望數量。**它必須是 `Option`**：萬用字元表示「現在有幾台就
 *  連幾台」，少建一台 VM 會看起來完全正常，正好吃掉本工具的核心價值。
 *  因此沒填 `expect` 要能被 lint 抓出來（L005），型別就不能強制它存在。
 */
({ pattern: {
	slug_pattern: string,
	/**
	 *  只算這個 [`DeploymentNode`] 底下的（含所有子孫）。
	 * 
	 *  # 為什麼需要它
	 * 
	 *  `redis-* expect 6` 只數總量。有人把一台機器從主中心搬到異地，
	 *  總數還是 6，**lint 不會叫**——而那正是這個工具存在的理由。
	 * 
	 *  拆成兩條「主中心 3 台」「異地 3 台」就抓得到。而站點資訊
	 *  **本來就在模型裡**（Instance 住在 VM 裡，VM 住在站點裡），
	 *  所以不需要新的 Cluster 概念，只需要能限定範圍。
	 * 
	 *  順帶好處：站點不必再編進 slug（`redis-main-01`）。
	 *  名字編了資訊就會說謊——機器搬家之後 slug 不會自己改。
	 */
	within?: Id | null,
	/**
	 *  用 `u32` 而不是 `usize`：這是「期望有幾台機器」，不是記憶體索引。
	 *  而且 `usize` 不能匯出成 TypeScript（specta 怕 BigInt 精度問題）。
	 */
	expect?: number | null,
} }) & { one?: never };

/**  [`blank`] 要建哪一種。跟 [`Resource`] 分開，因為前端要先選種類才有內容。 */
export type Kind = "person" | "system" | "container" | "endpointDef" | "relationship" | "environment" | "node" | "infra" | "infraEndpoint" | "instance" | "systemInstance";

/**
 *  圖上的一條線。
 * 
 *  `connection` **會重複**——一條萬用字元連線長出好幾條線。圖上的形狀
 *  靠 `loomId` 唯一，線不靠。對帳那邊在收下之前會依 `connection` 去重。
 */
export type Link = {
	/**  這條線屬於哪條實際連線。 */
	connection: Id,
	/**  起點的形狀 id。 */
	from: Id,
	/**  終點的形狀 id。 */
	to: Id,
	/**  起點是不是「人」。人不住在環境裡，圖上要另外補一個形狀。 */
	fromPerson: boolean,
	/**
	 *  備援線在圖上要看得出來——它一樣要建、防火牆一樣要開，
	 *  但把它跟平常的資料流畫成一樣重，圖會很吵而且讀不出主路徑。
	 */
	kind: ConnectionKind,
	/**  線上的字。空白會被 L007 叫。 */
	purpose: string,
};

/**  讀回來的一張圖。 */
export type Loaded = {
	xml: string,
	/**  這張圖畫的是哪一版模型。存檔時要拿它跟當下的比。 */
	model: string,
};

/**  邏輯層的全部內容。 */
export type Logical = Logical_Serialize | Logical_Deserialize;

/**  邏輯層的全部內容。 */
export type Logical_Deserialize = {
	people: Person_Deserialize[],
	systems: SoftwareSystem_Deserialize[],
	containers: Container_Deserialize[],
	relationships: Relationship_Deserialize[],
};

/**  邏輯層的全部內容。 */
export type Logical_Serialize = {
	people: Person_Serialize[],
	systems: SoftwareSystem_Serialize[],
	containers: Container_Serialize[],
	relationships: Relationship_Serialize[],
};

/**  整張矩陣。列是邏輯連線，欄是環境。 */
export type Matrix = {
	/**  列的順序，與 `project.logical.relationships` 相同。 */
	relationships: Id[],
	/**  欄的順序，與 `project.environments` 相同。 */
	environments: Id[],
	/**  每格一項，依 (relationship, environment) 排列，長度為兩者相乘。 */
	cells: Cell[],
};

/**
 *  前端要顯示的東西。**不含 token**——狀態會被畫面到處傳，
 *  而 token 只該在使用者主動要求時出現一次（見 [`config_snippet`]）。
 */
export type McpStatus = {
	running: boolean,
	url: string | null,
	/**  想用的埠。`None` 表示交給作業系統挑。 */
	preferredPort: number | null,
	requireToken: boolean,
	autostart: boolean,
	/**  開機自動啟用失敗了的話，原因。成功或沒開自動啟用時是 `None`。 */
	autostartFailed: string | null,
};

/**  運算載體的種類。 */
export type NodeKind = 
/**
 *  機房、園區、可用區——**裝別的節點用的**，本身不跑東西。
 * 
 *  C4 的 Deployment Node 本來就可巢狀，站點是它最常見的外層用法。
 *  沒有這個種類的話，「主中心」只能勉強標成實體機，畫出來會變成一台機器。
 */
"site" | "physical" | "virtual-machine" | "linux-container";

/**
 *  開啟的結果。
 * 
 *  「已經開在別的視窗」不是錯誤——使用者只是選了一個他已經在看的東西，
 *  而正確的回應是把那扇窗叫到前面。做成錯誤的話畫面會跳紅字，
 *  像是他做錯了什麼。
 */
export type OpenOutcome = OpenOutcome_Serialize | OpenOutcome_Deserialize;

/**
 *  開啟的結果。
 * 
 *  「已經開在別的視窗」不是錯誤——使用者只是選了一個他已經在看的東西，
 *  而正確的回應是把那扇窗叫到前面。做成錯誤的話畫面會跳紅字，
 *  像是他做錯了什麼。
 */
export type OpenOutcome_Deserialize = 
/**  開好了，這扇視窗現在看的是它。 */
({ loaded: Snapshot_Deserialize }) & { elsewhere?: never } | 
/**  已經開在另一扇視窗，那扇已經被叫到前面了。這扇視窗維持原狀。 */
({ elsewhere: {
	name: string,
} }) & { loaded?: never };

/**
 *  開啟的結果。
 * 
 *  「已經開在別的視窗」不是錯誤——使用者只是選了一個他已經在看的東西，
 *  而正確的回應是把那扇窗叫到前面。做成錯誤的話畫面會跳紅字，
 *  像是他做錯了什麼。
 */
export type OpenOutcome_Serialize = 
/**  開好了，這扇視窗現在看的是它。 */
({ loaded: Snapshot_Serialize }) & { elsewhere?: never } | 
/**  已經開在另一扇視窗，那扇已經被叫到前面了。這扇視窗維持原狀。 */
({ elsewhere: {
	name: string,
} }) & { loaded?: never };

/**  真人使用者。C4 的 `Person`，只出現在 Context 圖。 */
export type Person = Person_Serialize | Person_Deserialize;

/**  真人使用者。C4 的 `Person`，只出現在 Context 圖。 */
export type Person_Deserialize = {
	id: Id,
	slug: string,
	name: string,
	/**  使用者的備註。見 [`crate::memo_is_empty`]。 */
	memo?: string,
};

/**  真人使用者。C4 的 `Person`，只出現在 Context 圖。 */
export type Person_Serialize = {
	id: Id,
	slug: string,
	name: string,
	/**  使用者的備註。見 [`crate::memo_is_empty`]。 */
	memo?: string,
};

export type Plan = {
	changes: Change[],
	/**  檔案裡有、但內容完全相同的項目數。重新匯入時這個數字會很大。 */
	unchanged: number,
	/**  importer 自己的計數與警告（例如位址衝突）。 */
	warnings: string[],
	/**  這份檔案會動到哪些環境。 */
	environments: string[],
};

/**
 *  一個專案：一份邏輯層母版，加上多個環境。
 *  一個完整的專案。
 * 
 *  存檔時會被 [`repository`] 拆成多個 YAML 檔，所以磁碟上沒有「一個 Project 檔」。
 *  但它整份會跨過 Tauri 邊界送到前端當唯讀鏡像，因此需要序列化。
 */
export type Project = Project_Serialize | Project_Deserialize;

/**
 *  一個專案：一份邏輯層母版，加上多個環境。
 *  一個完整的專案。
 * 
 *  存檔時會被 [`repository`] 拆成多個 YAML 檔，所以磁碟上沒有「一個 Project 檔」。
 *  但它整份會跨過 Tauri 邊界送到前端當唯讀鏡像，因此需要序列化。
 */
export type Project_Deserialize = {
	id: Id,
	slug: string,
	name: string,
	/**  使用者的備註。見 [`memo_is_empty`]。 */
	memo?: string,
	logical: Logical_Deserialize,
	environments: Environment_Deserialize[],
};

/**
 *  一個專案：一份邏輯層母版，加上多個環境。
 *  一個完整的專案。
 * 
 *  存檔時會被 [`repository`] 拆成多個 YAML 檔，所以磁碟上沒有「一個 Project 檔」。
 *  但它整份會跨過 Tauri 邊界送到前端當唯讀鏡像，因此需要序列化。
 */
export type Project_Serialize = {
	id: Id,
	slug: string,
	name: string,
	/**  使用者的備註。見 [`memo_is_empty`]。 */
	memo?: string,
	logical: Logical_Serialize,
	environments: Environment_Serialize[],
};

/**  照契約擬一條連線。 */
export type Proposal = Proposal_Serialize | Proposal_Deserialize;

/**  照契約擬一條連線。 */
export type Proposal_Deserialize = {
	/**
	 *  先在這裡發好 id，套用時就不必再產一個。
	 * 
	 *  這樣 `apply` 是決定性的：預覽算出來的結果跟真正套用的完全一樣，
	 *  復原重做也會重播出同一條連線而不是每次換一個 UUID。
	 */
	id: Id,
	serves: Id,
	purpose: string,
	/**  擬不出來時是 `None`（例如來源在這個環境根本沒有實體）。 */
	from: Endpointing_Deserialize | null,
	to: Endpointing_Deserialize | null,
	/**  這份提案做了哪些假設、哪裡擬不出來。**一定要顯示給使用者看。** */
	notes: string[],
};

/**  照契約擬一條連線。 */
export type Proposal_Serialize = {
	/**
	 *  先在這裡發好 id，套用時就不必再產一個。
	 * 
	 *  這樣 `apply` 是決定性的：預覽算出來的結果跟真正套用的完全一樣，
	 *  復原重做也會重播出同一條連線而不是每次換一個 UUID。
	 */
	id: Id,
	serves: Id,
	purpose: string,
	/**  擬不出來時是 `None`（例如來源在這個環境根本沒有實體）。 */
	from: Endpointing_Serialize | null,
	to: Endpointing_Serialize | null,
	/**  這份提案做了哪些假設、哪裡擬不出來。**一定要顯示給使用者看。** */
	notes: string[],
};

/**
 *  Endpoint 的協定種類。
 * 
 *  「Port」這個詞不夠準確——Unix socket、JDBC URL 與檔案都不是 port，
 *  它們的共通點是「服務對外的一個接點」，因此統一叫 Endpoint。
 */
export type Protocol = "tcp" | "udp" | "unix-socket" | "jdbc" | "file";

/**
 *  邏輯層的連線：「A 要連 B 的某個 endpoint」，並說明用途。
 * 
 *  **這就是原本討論中的「連線契約」。** 我們刻意不另設 placeholder 概念——
 *  邏輯層宣告了一條連線，每個環境就必須實現它，沒實現就是 lint 錯誤。
 * 
 *  一條 Relationship 在不同環境會展開成**不同數量**的實際連線：
 *  dev 直連是 1 段，prod 走 F5 是 2 段；Redis 叢集 prod 12 個節點、test 6 個。
 */
export type Relationship = Relationship_Serialize | Relationship_Deserialize;

/**
 *  邏輯連線的一端：自家的服務、一整個外部系統，或一個真人。
 * 
 *  外部系統不拆成 Container，所以它整個就是一端。
 */
export type RelationshipEnd = ({ container: Id }) & { person?: never; system?: never } | ({ system: Id }) & { container?: never; person?: never } | 
/**
 *  真人。**只該出現在來源端**——「使用者連上系統」是 C4 Context 圖
 *  最常見的關係，沒有它整條進入點的流量就少了最前面那一段。
 * 
 *  人不需要被部署，所以 L001 不會要求它在每個環境都有實體。
 */
({ person: Id }) & { container?: never; system?: never };

/**
 *  邏輯層的連線：「A 要連 B 的某個 endpoint」，並說明用途。
 * 
 *  **這就是原本討論中的「連線契約」。** 我們刻意不另設 placeholder 概念——
 *  邏輯層宣告了一條連線，每個環境就必須實現它，沒實現就是 lint 錯誤。
 * 
 *  一條 Relationship 在不同環境會展開成**不同數量**的實際連線：
 *  dev 直連是 1 段，prod 走 F5 是 2 段；Redis 叢集 prod 12 個節點、test 6 個。
 */
export type Relationship_Deserialize = {
	id: Id,
	slug: string,
	/**  用途說明。空白會觸發 L007。 */
	purpose: string,
	from: RelationshipEnd,
	to: RelationshipEnd,
	/**
	 *  連到目標的哪一個 [`EndpointDef`]。
	 *  目標是 Container 就查它的 endpoints，是外部系統就查系統的 endpoints。
	 */
	to_endpoint: Id,
	/**
	 *  使用者的備註。見 [`crate::memo_is_empty`]。
	 * 
	 *  跟 `purpose` 分開：`purpose` 是 L007 在檢查的欄位，屬於「這條連線為什麼存在」；
	 *  備註是規則不管的雜項，寫進 `purpose` 會讓那個欄位變成雜物櫃。
	 */
	memo?: string,
};

/**
 *  邏輯層的連線：「A 要連 B 的某個 endpoint」，並說明用途。
 * 
 *  **這就是原本討論中的「連線契約」。** 我們刻意不另設 placeholder 概念——
 *  邏輯層宣告了一條連線，每個環境就必須實現它，沒實現就是 lint 錯誤。
 * 
 *  一條 Relationship 在不同環境會展開成**不同數量**的實際連線：
 *  dev 直連是 1 段，prod 走 F5 是 2 段；Redis 叢集 prod 12 個節點、test 6 個。
 */
export type Relationship_Serialize = {
	id: Id,
	slug: string,
	/**  用途說明。空白會觸發 L007。 */
	purpose: string,
	from: RelationshipEnd,
	to: RelationshipEnd,
	/**
	 *  連到目標的哪一個 [`EndpointDef`]。
	 *  目標是 Container 就查它的 endpoints，是外部系統就查系統的 endpoints。
	 */
	to_endpoint: Id,
	/**
	 *  使用者的備註。見 [`crate::memo_is_empty`]。
	 * 
	 *  跟 `purpose` 分開：`purpose` 是 L007 在檢查的欄位，屬於「這條連線為什麼存在」；
	 *  備註是規則不管的雜項，寫進 `purpose` 會讓那個欄位變成雜物櫃。
	 */
	memo?: string,
};

/**
 *  一個可以增／改／刪的模型元素。
 * 
 *  帶的是**完整的值**而不是「欄位差異」：整份換掉的語意最單純，
 *  而復原本來就是存整份快照（見 [`crate::history`]），省不了什麼。
 */
export type Resource = Resource_Serialize | Resource_Deserialize;

/**
 *  表格的一列。
 * 
 *  名字不叫 `Row`，是為了不跟 [`crate::table::Row`]（連線表的一列）撞名——
 *  型別匯出到 TypeScript 之後是同一個命名空間，撞了就產不出來。
 */
export type ResourceRow = ResourceRow_Serialize | ResourceRow_Deserialize;

/**
 *  表格的一列。
 * 
 *  名字不叫 `Row`，是為了不跟 [`crate::table::Row`]（連線表的一列）撞名——
 *  型別匯出到 TypeScript 之後是同一個命名空間，撞了就產不出來。
 */
export type ResourceRow_Deserialize = {
	id: Id,
	/**  已經算好的格子，順序對應 [`Table::columns`]。 */
	cells: string[],
	/**  縮排層級。只有機器會用到（站點 → 機器 → 機器）。 */
	depth: number,
	/**  這一列身上有沒有 lint 問題。有的話畫面上點一下就能跳過去。 */
	severity: Severity | null,
	/**  編輯表單的起點。 */
	resource: Resource_Deserialize,
};

/**
 *  表格的一列。
 * 
 *  名字不叫 `Row`，是為了不跟 [`crate::table::Row`]（連線表的一列）撞名——
 *  型別匯出到 TypeScript 之後是同一個命名空間，撞了就產不出來。
 */
export type ResourceRow_Serialize = {
	id: Id,
	/**  已經算好的格子，順序對應 [`Table::columns`]。 */
	cells: string[],
	/**  縮排層級。只有機器會用到（站點 → 機器 → 機器）。 */
	depth: number,
	/**  這一列身上有沒有 lint 問題。有的話畫面上點一下就能跳過去。 */
	severity: Severity | null,
	/**  編輯表單的起點。 */
	resource: Resource_Serialize,
};

/**
 *  一個可以增／改／刪的模型元素。
 * 
 *  帶的是**完整的值**而不是「欄位差異」：整份換掉的語意最單純，
 *  而復原本來就是存整份快照（見 [`crate::history`]），省不了什麼。
 */
export type Resource_Deserialize = ({ person: Person_Deserialize }) & { container?: never; endpointDef?: never; environment?: never; infra?: never; infraEndpoint?: never; instance?: never; node?: never; relationship?: never; system?: never; systemInstance?: never } | ({ system: SoftwareSystem_Deserialize }) & { container?: never; endpointDef?: never; environment?: never; infra?: never; infraEndpoint?: never; instance?: never; node?: never; person?: never; relationship?: never; systemInstance?: never } | ({ container: Container_Deserialize }) & { endpointDef?: never; environment?: never; infra?: never; infraEndpoint?: never; instance?: never; node?: never; person?: never; relationship?: never; system?: never; systemInstance?: never } | 
/**  接點定義掛在服務或外部系統身上，所以要指名擁有者。 */
({ endpointDef: {
	owner: Id,
	def: EndpointDef_Deserialize,
} }) & { container?: never; environment?: never; infra?: never; infraEndpoint?: never; instance?: never; node?: never; person?: never; relationship?: never; system?: never; systemInstance?: never } | ({ relationship: Relationship_Deserialize }) & { container?: never; endpointDef?: never; environment?: never; infra?: never; infraEndpoint?: never; instance?: never; node?: never; person?: never; system?: never; systemInstance?: never } | ({ environment: Environment_Deserialize }) & { container?: never; endpointDef?: never; infra?: never; infraEndpoint?: never; instance?: never; node?: never; person?: never; relationship?: never; system?: never; systemInstance?: never } | 
/**  站點、實體機、VM、Linux 容器。`within` 是父節點。 */
({ node: {
	environment: Id,
	within: Id | null,
	node: DeploymentNode_Deserialize,
} }) & { container?: never; endpointDef?: never; environment?: never; infra?: never; infraEndpoint?: never; instance?: never; person?: never; relationship?: never; system?: never; systemInstance?: never } | 
/**  F5 這類 VIP 設備。 */
({ infra: {
	environment: Id,
	node: InfrastructureNode_Deserialize,
} }) & { container?: never; endpointDef?: never; environment?: never; infraEndpoint?: never; instance?: never; node?: never; person?: never; relationship?: never; system?: never; systemInstance?: never } | 
/**  設備上的一個 VIP。設備不對應邏輯層元素，所以它的接點沒有 `def`。 */
({ infraEndpoint: {
	environment: Id,
	node: Id,
	endpoint: Endpoint_Deserialize,
} }) & { container?: never; endpointDef?: never; environment?: never; infra?: never; instance?: never; node?: never; person?: never; relationship?: never; system?: never; systemInstance?: never } | 
/**
 *  一個服務在某台機器上跑起來的那一份。**位址就住在這裡。**
 * 
 *  `node` 是它跑在哪台機器上。服務實體不能離開機器獨立存在——
 *  「東西跑在哪裡」正是部署圖唯一要回答的問題。
 */
({ instance: {
	environment: Id,
	node: Id,
	instance: ContainerInstance_Deserialize,
} }) & { container?: never; endpointDef?: never; environment?: never; infra?: never; infraEndpoint?: never; node?: never; person?: never; relationship?: never; system?: never; systemInstance?: never } | 
/**  外部系統在這個環境的實體。 */
({ systemInstance: {
	environment: Id,
	instance: SoftwareSystemInstance_Deserialize,
} }) & { container?: never; endpointDef?: never; environment?: never; infra?: never; infraEndpoint?: never; instance?: never; node?: never; person?: never; relationship?: never; system?: never };

/**
 *  一個可以增／改／刪的模型元素。
 * 
 *  帶的是**完整的值**而不是「欄位差異」：整份換掉的語意最單純，
 *  而復原本來就是存整份快照（見 [`crate::history`]），省不了什麼。
 */
export type Resource_Serialize = ({ person: Person_Serialize }) & { container?: never; endpointDef?: never; environment?: never; infra?: never; infraEndpoint?: never; instance?: never; node?: never; relationship?: never; system?: never; systemInstance?: never } | ({ system: SoftwareSystem_Serialize }) & { container?: never; endpointDef?: never; environment?: never; infra?: never; infraEndpoint?: never; instance?: never; node?: never; person?: never; relationship?: never; systemInstance?: never } | ({ container: Container_Serialize }) & { endpointDef?: never; environment?: never; infra?: never; infraEndpoint?: never; instance?: never; node?: never; person?: never; relationship?: never; system?: never; systemInstance?: never } | 
/**  接點定義掛在服務或外部系統身上，所以要指名擁有者。 */
({ endpointDef: {
	owner: Id,
	def: EndpointDef_Serialize,
} }) & { container?: never; environment?: never; infra?: never; infraEndpoint?: never; instance?: never; node?: never; person?: never; relationship?: never; system?: never; systemInstance?: never } | ({ relationship: Relationship_Serialize }) & { container?: never; endpointDef?: never; environment?: never; infra?: never; infraEndpoint?: never; instance?: never; node?: never; person?: never; system?: never; systemInstance?: never } | ({ environment: Environment_Serialize }) & { container?: never; endpointDef?: never; infra?: never; infraEndpoint?: never; instance?: never; node?: never; person?: never; relationship?: never; system?: never; systemInstance?: never } | 
/**  站點、實體機、VM、Linux 容器。`within` 是父節點。 */
({ node: {
	environment: Id,
	within: Id | null,
	node: DeploymentNode_Serialize,
} }) & { container?: never; endpointDef?: never; environment?: never; infra?: never; infraEndpoint?: never; instance?: never; person?: never; relationship?: never; system?: never; systemInstance?: never } | 
/**  F5 這類 VIP 設備。 */
({ infra: {
	environment: Id,
	node: InfrastructureNode_Serialize,
} }) & { container?: never; endpointDef?: never; environment?: never; infraEndpoint?: never; instance?: never; node?: never; person?: never; relationship?: never; system?: never; systemInstance?: never } | 
/**  設備上的一個 VIP。設備不對應邏輯層元素，所以它的接點沒有 `def`。 */
({ infraEndpoint: {
	environment: Id,
	node: Id,
	endpoint: Endpoint_Serialize,
} }) & { container?: never; endpointDef?: never; environment?: never; infra?: never; instance?: never; node?: never; person?: never; relationship?: never; system?: never; systemInstance?: never } | 
/**
 *  一個服務在某台機器上跑起來的那一份。**位址就住在這裡。**
 * 
 *  `node` 是它跑在哪台機器上。服務實體不能離開機器獨立存在——
 *  「東西跑在哪裡」正是部署圖唯一要回答的問題。
 */
({ instance: {
	environment: Id,
	node: Id,
	instance: ContainerInstance_Serialize,
} }) & { container?: never; endpointDef?: never; environment?: never; infra?: never; infraEndpoint?: never; node?: never; person?: never; relationship?: never; system?: never; systemInstance?: never } | 
/**  外部系統在這個環境的實體。 */
({ systemInstance: {
	environment: Id,
	instance: SoftwareSystemInstance_Serialize,
} }) & { container?: never; endpointDef?: never; environment?: never; infra?: never; infraEndpoint?: never; instance?: never; node?: never; person?: never; relationship?: never; system?: never };

/**  表格的一列。 */
export type Row = {
	id: Id,
	environment: Id,
	/**  它服務哪條契約。 */
	serves: Id,
	/**  契約的顯示名。找不到對應契約時是 `None`（那本身就是 L003）。 */
	servesSlug: string | null,
	purpose: string,
	/**
	 *  正常路徑還是備援路徑。畫面上用來區分——備援跟正常長得一樣的話，
	 *  讀的人分不出平常的資料流是哪幾條。
	 */
	kind: ConnectionKind,
	from: Side,
	to: Side,
	/**  這一列自己的嚴重度。沒問題時是 `None`。 */
	severity: Severity | null,
	rules: Rule[],
	/**
	 *  這一列牽涉到的所有模型元素 id：連線自己、它服務的契約、
	 *  兩端解析出來的 Instance／設備／外部系統／人，以及用到的 Endpoint。
	 * 
	 *  # 為什麼需要它
	 * 
	 *  Lint 面板上點一項發現，要能跳到**那一列**。但發現的 `subject`
	 *  不一定是連線 id——L006 指的是 Endpoint、L008 指的是 Instance。
	 *  「這個 id 對應到哪幾列」得走一次萬用字元展開才知道，
	 *  那跟 lint 是同一套邏輯，放前端就是寫第二遍。
	 */
	subjects: Id[],
};

/**  規則代號。序列化後就是 `"L001"` 這種字串，跟文件一致。 */
export type Rule = 
/**  邏輯層元素在某環境沒有任何實現。 */
"L001" | 
/**  某條 Relationship 在某環境走不通（可達性斷裂）。 */
"L002" | 
/**  連線指向不存在的 Instance、設備或 Endpoint。 */
"L003" | 
/**  萬用字元的實際數量與 `expect` 不符。 */
"L004" | 
/**  萬用字元沒有註明 `expect`。 */
"L005" | 
/**  Endpoint 缺少實際位址。 */
"L006" | 
/**  連線沒有填用途。 */
"L007" | 
/**  某 Instance 沒有被任何連線碰到。 */
"L008" | 
/**
 *  模型元素指向一個不存在的模型元素。
 * 
 *  # 為什麼需要一條獨立的規則
 * 
 *  L003 管的是「**連線**指到不存在的東西」。但元素之間也互相指：
 *  服務實體指著服務、契約指著服務與接點、接點指著接點定義。
 * 
 *  沒有這條的話，刪掉一個服務會**安靜地**留下一批指著空氣的服務實體——
 *  lint 一句話都不說，而那正是這個工具存在要抓的東西。
 *  所以它是「可以刪除邏輯層元素」的前置條件，不是加分項。
 * 
 *  代號接在 draw.io 那三條（L009–L011）後面，是因為那三條先被寫進文件。
 */
"L012" | 
/**
 *  契約的**目標端**是人。
 * 
 *  # 為什麼這需要一條規則
 * 
 *  `RelationshipEnd::Person` 的註解寫著「**只該出現在來源端**」——
 *  「使用者連上系統」是 C4 Context 圖最常見的關係，但反過來沒有意義：
 *  人沒有接點、沒有位址、也不會被部署。
 * 
 *  而那句話一直只是註解。在這條規則之前，把人放到目標端是**完全安靜**的：
 * 
 *  - `missing_relationship_end` 只檢查那個人存在，他確實存在
 *  - `target_has_endpoint` 對人直接回 `true`，因為人本來就沒有接點
 *  - 可達性 BFS 把人當成葉節點，走到他就停了，不算斷裂
 * 
 *  於是模型裡留下一條永遠不可能被實現的契約，而工具一句話都不說。
 *  對一個賣點是「怕漏」的工具，「說沒問題但東西是錯的」是最糟的狀態。
 */
"L013" | 
/**
 *  同一個環境裡，兩個不同種類的東西叫同一個名字。
 * 
 *  # 為什麼這值得叫
 * 
 *  新增時的唯一性檢查是**分開的**：服務實體只跟服務實體比、設備只跟
 *  設備比、外部系統實體只跟外部系統實體比。所以一台叫 `pay-01` 的
 *  服務實體與一台叫 `pay-01` 的設備可以同時存在，兩邊的檢查都會過。
 * 
 *  但 Agent 是**用名字**指涉東西的（`loom-mcp` 的 `refs`），而它依序找
 *  服務實體 → 設備 → 外部系統實體，**先找到的贏**。於是「連到 pay-01」
 *  會安靜地接到服務實體上，而使用者要的是那台設備——連線看起來完全正常。
 * 
 *  `refs` 的註解一直寫著「名字撞在一起本來就是該被 lint 抓的問題」。
 *  這條就是那個 lint。
 * 
 *  # 為什麼是警告不是錯誤
 * 
 *  資料本身沒有壞，壞的是「用名字指涉」這一條路。而現實中 VIP 跟它
 *  服務的那個東西同名是有可能的，用錯誤會變成一個拿不掉的紅字。
 */
"L014";

export type Severity = "info" | "warning" | "error";

/**  連線的一端，已經解析成看得懂的東西。 */
export type Side = {
	kind: SideKind,
	/**  顯示名。萬用字元保留原樣（`redis-*`），使用者才看得出這是一群。 */
	label: string,
	/**  接點的顯示名。來源端可以沒有（由 OS 分配 ephemeral port）。 */
	endpoint: string | null,
	/**  實際位址。萬用字元會有多個。 */
	addresses: string[],
	/**  萬用字元展開成幾個。不是萬用字元時是 1。 */
	matched: number,
	/**  註明的期望數量。 */
	expect: number | null,
};

/**  連線的一端指向什麼。畫面上用不同的圖示區分。 */
export type SideKind = 
/**  一台或一群服務實體。 */
"instance" | 
/**  F5 這類設備。 */
"infra" | 
/**  外部系統的實體。 */
"system" | 
/**  真人。只會出現在來源端。 */
"person";

/**
 *  開一個專案之後，前端需要的所有東西一次給齊。
 * 
 *  分成三個 command 來回問會有中間狀態（模型換了但 lint 還是舊的），
 *  畫面就會短暫地自相矛盾。
 */
export type Snapshot = Snapshot_Serialize | Snapshot_Deserialize;

/**
 *  開一個專案之後，前端需要的所有東西一次給齊。
 * 
 *  分成三個 command 來回問會有中間狀態（模型換了但 lint 還是舊的），
 *  畫面就會短暫地自相矛盾。
 */
export type Snapshot_Deserialize = {
	root: string,
	project: Project_Deserialize,
	findings: FindingView[],
	matrix: Matrix,
	/**  連線表用的列。跟矩陣一樣，是同一份資料的另一種排法。 */
	rows: Row[],
	/**  目前內容跟磁碟上不一樣。關視窗前要問的就是這個。 */
	dirty: boolean,
	/**  復原／重做選單要顯示的短標籤。`None` 表示按鈕要停用。 */
	undoLabel: string | null,
	redoLabel: string | null,
};

/**
 *  開一個專案之後，前端需要的所有東西一次給齊。
 * 
 *  分成三個 command 來回問會有中間狀態（模型換了但 lint 還是舊的），
 *  畫面就會短暫地自相矛盾。
 */
export type Snapshot_Serialize = {
	root: string,
	project: Project_Serialize,
	findings: FindingView[],
	matrix: Matrix,
	/**  連線表用的列。跟矩陣一樣，是同一份資料的另一種排法。 */
	rows: Row[],
	/**  目前內容跟磁碟上不一樣。關視窗前要問的就是這個。 */
	dirty: boolean,
	/**  復原／重做選單要顯示的短標籤。`None` 表示按鈕要停用。 */
	undoLabel: string | null,
	redoLabel: string | null,
};

/**  軟體系統。可能是自家系統，也可能是外部系統（金流、簡訊商）。 */
export type SoftwareSystem = SoftwareSystem_Serialize | SoftwareSystem_Deserialize;

/**
 *  外部系統在此環境的實體。C4 的 `Software System Instance`。
 * 
 *  例如金流系統：prod 用正式閘道，test 用 sandbox。
 *  它**不放在 [`DeploymentNode`] 底下**——那些機器不是我們的，我們只知道位址。
 */
export type SoftwareSystemInstance = SoftwareSystemInstance_Serialize | SoftwareSystemInstance_Deserialize;

/**
 *  外部系統在此環境的實體。C4 的 `Software System Instance`。
 * 
 *  例如金流系統：prod 用正式閘道，test 用 sandbox。
 *  它**不放在 [`DeploymentNode`] 底下**——那些機器不是我們的，我們只知道位址。
 */
export type SoftwareSystemInstance_Deserialize = {
	id: Id,
	slug: string,
	system: Id,
	endpoints?: Endpoint_Deserialize[],
	/**  同 [`ContainerInstance::standalone`]，關閉 L008 警告。 */
	standalone?: boolean,
	/**  使用者的備註。見 [`crate::memo_is_empty`]。 */
	memo?: string,
};

/**
 *  外部系統在此環境的實體。C4 的 `Software System Instance`。
 * 
 *  例如金流系統：prod 用正式閘道，test 用 sandbox。
 *  它**不放在 [`DeploymentNode`] 底下**——那些機器不是我們的，我們只知道位址。
 */
export type SoftwareSystemInstance_Serialize = {
	id: Id,
	slug: string,
	system: Id,
	endpoints?: Endpoint_Serialize[],
	/**  同 [`ContainerInstance::standalone`]，關閉 L008 警告。 */
	standalone?: boolean,
	/**  使用者的備註。見 [`crate::memo_is_empty`]。 */
	memo?: string,
};

/**  軟體系統。可能是自家系統，也可能是外部系統（金流、簡訊商）。 */
export type SoftwareSystem_Deserialize = {
	id: Id,
	slug: string,
	name: string,
	/**
	 *  外部系統不由我們部署，但仍需在每個環境指定它的位址
	 *  （例如測試環境用金流 sandbox）。
	 */
	external: boolean,
	/**
	 *  外部系統對外的接點定義。
	 * 
	 *  C4 不把外部系統拆成 Container——我們看不到人家內部長怎樣，
	 *  只知道「有一個 API 可以打」。因此接點直接掛在系統上。
	 *  自家系統留空，它的接點由各個 [`Container`] 自己定義。
	 */
	endpoints?: EndpointDef_Deserialize[],
	/**  使用者的備註。見 [`crate::memo_is_empty`]。 */
	memo?: string,
};

/**  軟體系統。可能是自家系統，也可能是外部系統（金流、簡訊商）。 */
export type SoftwareSystem_Serialize = {
	id: Id,
	slug: string,
	name: string,
	/**
	 *  外部系統不由我們部署，但仍需在每個環境指定它的位址
	 *  （例如測試環境用金流 sandbox）。
	 */
	external: boolean,
	/**
	 *  外部系統對外的接點定義。
	 * 
	 *  C4 不把外部系統拆成 Container——我們看不到人家內部長怎樣，
	 *  只知道「有一個 API 可以打」。因此接點直接掛在系統上。
	 *  自家系統留空，它的接點由各個 [`Container`] 自己定義。
	 */
	endpoints?: EndpointDef_Serialize[],
	/**  使用者的備註。見 [`crate::memo_is_empty`]。 */
	memo?: string,
};

/**  一格的狀態。畫面上用顏色區分，順序即嚴重度。 */
export type Status = 
/**  沒有任何問題。 */
"realized" | 
/**  有警告，但路是通的。 */
"warning" | 
/**  有錯誤，但至少畫了連線。例如走不通、數量對不上。 */
"broken" | 
/**  這個環境完全沒有實現這條契約——**這就是使用者最怕的那格**。 */
"missing";

/**  一種資源的一張表。 */
export type Table = Table_Serialize | Table_Deserialize;

/**
 *  這張表歸哪一層管。
 * 
 *  # 為什麼這是模型知識，不是排版偏好
 * 
 *  **母版與分身的分界是整個領域模型最重要的一件事。** 分頁列若把兩者
 *  畫成同一串，等於在跟使用者說「這些都差不多」。哪張表屬於哪一層
 *  不是畫面決定的，所以由這裡講，前端只負責照著畫分隔線。
 */
export type TableGroup = 
/**
 *  專案層級：不屬於任何一層。
 * 
 *  只有「環境」這張表。它列的是**全部**環境，所以不隸屬於某一個環境；
 *  但它也顯然不是邏輯層的東西。畫面上它不進分頁列，改由環境選單裡的
 *  「管理環境…」開出來——那正是使用者會去找它的地方。
 */
"project" | 
/**  邏輯層（母版）：定義「有哪些服務、誰要連誰」。 */
"logical" | 
/**  環境層（分身）：填「實際跑在哪台機器、IP 是什麼」。 */
"environment";

/**  一種資源的一張表。 */
export type Table_Deserialize = {
	kind: Kind,
	/**  分頁上的字，例如「服務」。 */
	title: string,
	group: TableGroup,
	columns: string[],
	rows: ResourceRow_Deserialize[],
	/**  這張表屬於哪個環境。邏輯層的表是 `None`。 */
	environment: Id | null,
	/**  沒有半列時要說什麼。空白的表格看起來像壞掉。 */
	emptyHint: string,
};

/**  一種資源的一張表。 */
export type Table_Serialize = {
	kind: Kind,
	/**  分頁上的字，例如「服務」。 */
	title: string,
	group: TableGroup,
	columns: string[],
	rows: ResourceRow_Serialize[],
	/**  這張表屬於哪個環境。邏輯層的表是 `None`。 */
	environment: Id | null,
	/**  沒有半列時要說什麼。空白的表格看起來像壞掉。 */
	emptyHint: string,
};

/**  一個可以被指定的模型元素。 */
export type Target = {
	id: Id,
	kind: ElementKind,
	label: string,
};

/**  圖上一個沒有 `loomId` 的形狀。由 JS 從 XML 挖出來。 */
export type UnboundShape = {
	/**  XML 裡的 cell id。指定時要改的就是它，所以它是這裡唯一的身分。 */
	cell: string,
	/**
	 *  圖上的文字。**可能是空的**——沒有文字的形狀通常是裝飾，
	 *  但它仍然要送進來，否則畫面上的「還剩幾個」會少算。
	 */
	label: string,
	/**  是線還是框。線只能指給連線，框只能指給元素——見 [`annotate`]。 */
	edge?: boolean,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

